### ISSUE TITLE
[JsonIgnoreAttribute] ignored when using [KnownType(...)]

### ISSUE THREAD

**Issue by sarah-appsheet** [RSuter/NJsonSchema#246]
I am using _[KnownType(typeof(Foo))]_ on class **Bar**, and _[JsonIgnoreAttribute]_ on **Foo.IgnoreMe**. But **IgnoreMe** still gets included in the schema. Is this behavior intentional?

Ultimately I want to be able to flatten an inheritance hierarchy where properties like **IgnoreMe** occur in multiple classes in the hierarchy, creating conflicts.

**Comment by rsuter** [comment]
It seems that this is a bug... Can you post the two sample classes and the generated schema as well as the expected schema?

**Comment by sarah-appsheet** [comment]
Actually it looks like the JsonIgnoreAttribute isn't working at all for me, so I'll give a non-KnownType example:

```
public class Mno
{
    public string IncludeMe;

    [JsonIgnoreAttribute]
    public string IgnoreMe;
}

[DataContract]
public class Xyz
{
    [DataMember]
    public string IncludeMe;

    public string IgnoreMe;
}

var test1 = JsonSchema4.FromType<Mno>().ToJson();
/*
EXPECTED OUTPUT:
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "x-typeName": "Mno",
  "additionalProperties": false,
  "properties": {
    "IncludeMe": {
      "type": [
        "null",
        "string"
      ]
    }
  }
}

ACTUAL OUTPUT:
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "x-typeName": "Mno",
  "additionalProperties": false,
  "properties": {
    "IncludeMe": {
      "type": [
        "null",
        "string"
      ]
    },
    "IgnoreMe": {
      "type": [
        "null",
        "string"
      ]
    }
  }
}
*/

var test2 = 
/*
EXPECTED = ACTUAL OUTPUT:
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "x-typeName": "Xyz",
  "additionalProperties": false,
  "properties": {
    "IncludeMe": {
      "type": [
        "null",
        "string"
      ]
    }
  }
}
*/
```

**Comment by rsuter** [comment]
The problem is that you are using class fields instead of properties... Ill check if we can support this scenario as well...

**Comment by sarah-appsheet** [comment]
That would be cool. If it helps, I get the same results when I define properties thusly: public string IgnoreMe { get; set; }

**Comment by rsuter** [comment]
I just added unit tests for your code, and it works as expected... are you using the newest version?

**Comment by sarah-appsheet** [comment]
After checking, I did need to update from 5.13 to 5.16. It's still including ignored properties though.

```
public class Mno
{
    public string IncludeMe { get; set; }

    [JsonIgnoreAttribute]
    public string IgnoreMe { get; set; }
}

public class TestSchema
{
    public static string testMnoSchema()
    {
        return JsonSchema4.FromType<Mno>().ToJson();
    }
}
```

Result:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "x-typeName": "Mno",
  "additionalProperties": false,
  "properties": {
    "IncludeMe": {
      "type": [
        "null",
        "string"
      ]
    },
    "IgnoreMe": {
      "type": [
        "null",
        "string"
      ]
    }
  }
}
```

Is there anything else I should check? Interference from another library perhaps?

**Comment by rsuter** [comment]
This is strange.. can you provide a sample project?

**Comment by sarah-appsheet** [comment]
I'm working within a larger closed-source project, and not quite adept enough at C# and Visual Studio to know how to get a new project up and running.

**Comment by rsuter** [comment]
When running your sample code, I get the following JSON Schema: 

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "x-typeName": "Mno",
  "additionalProperties": false,
  "properties": {
    "IncludeMe": {
      "type": [
        "null",
        "string"
      ]
    }
  }
}
```

**Comment by rsuter** [comment]
Can you clone or download the NJsonSchema sources from GitHub and run the NJsonSchema.Demo application from the solution?

Just add a breakpoint: 

![image](https://cloud.githubusercontent.com/assets/2603405/20572144/843a7942-b1aa-11e6-93d7-f09f5aa4d170.png)

Is it working within this project?

**Comment by sarah-appsheet** [comment]
Yes, that works - I get the same thing as you. IgnoreMe is successfully ignored! I think there must be something in my project that is interfering with how JsonIgnoreAttribute is interpreted. Thanks for your help in narrowing it down.

**Comment by sarah-appsheet** [comment]
Turns out we had a duplicate JsonIgnoreAttribute in our codebase. If I use Newtonsoft.Json.JsonIgnoreAttribute, it works correctly. Excellent! However, it turns out some other part of our project has another use for the Newtonsoft attribute. Is there a way to define a custom ignore attribute?

**Comment by rsuter** [comment]
This is not possible... What is the other use case?

**Comment by sarah-appsheet** [comment]
We have the same classes being serialized in a couple of ways, for different purposes, so some properties need to be ignored in one context but not in the other. I think I can come up with workarounds for those properties, but that's the use case.

**Comment by RSuter** [comment]
Njs is now based on ContractResolver, you can now provide a custom one to exclude different properties...
