### ISSUE TITLE
StackOverflowException when loading Azure Resource Manager Template Json Schema

### ISSUE THREAD

**Issue by wangzq** [RSuter/NJsonSchema#298]
`await JsonSchema4.FromUrlAsync("http://schema.management.azure.com/schemas/2016-09-01/Microsoft.Resources.json");`

**Comment by wangzq** [comment]
Looks like caused by an incorrect `#ref` in one of the schema file: https://github.com/Azure/azure-resource-manager-schemas/pull/270/files; while the root cause is really in the json schema file, maybe we could do something here to detect such issue.

**Comment by wangzq** [comment]
According to https://tools.ietf.org/html/rfc6901 the `/` is required after `#`, therefore I think we should just throw an exception when the `$ref` starts with `#` but not `#/`.

**Comment by RSuter** [comment]
With the latest build, it works for me - it takes 40 seconds on my computer (mostly I/O web time)...
