### ISSUE TITLE
Retain data annotations on generated models

### ISSUE THREAD

**Issue by cbordeman** [RSuter/NJsonSchema#308]
Attributes such as [Required], [Range], [StringLength(5)] from the System.ComponentModel.DataAnnotations namespace should be retained in the generated client side models so validation can be performed.

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/commit/85a802083fad8833f5daf9e0a2d1626307c19633

**Comment by RSuter** [comment]
I think C# only as TypeScript/JS has no common way to express this...

**Comment by cbordeman** [comment]
Thanks very much for implementing this!
