### ISSUE TITLE
Use IContractResolver.ResolveContract instead of reflection for generator

### ISSUE THREAD

**Issue by RSuter** [RSuter/NJsonSchema#321]
```JsonContract ResolveContract(Type type)```

**Comment by markledwich2** [comment]
Looking forward to this. I have many discrepancies between the generated schema and my custom contract resolver that i use for serialization.  Using the branch solved most of my issues.

**Comment by rsuter** [comment]
Can you add some unit test to cover your problems?

**Comment by markledwich2** [comment]
#329

**Comment by rsuter** [comment]
Can you check the "use-contract-resolver" branch whether it solves your problems? I plan to merge this soon...

https://github.com/NJsonSchema/NJsonSchema/tree/use-contract-resolver

**Comment by markledwich2** [comment]
I tested this morning. I had one minor issue which i created tests for and fixed. See comments in  #345

**Comment by RSuter** [comment]
v9.0
