### ISSUE TITLE
schema.ToJson() raise an Error when trying to be executed in web 

### ISSUE THREAD

**Issue by moh-hassan** [RSuter/NJsonSchema#339]
I try to run NJsonSchema from Web using dotnetfiddle   [https://dotnetfiddle.net](https://dotnetfiddle.net)
The sample code is located in https://dotnetfiddle.net/Zs9R2u
and you can try it.

It raises the error: Fatal Error: Memory usage limit was exceeded
and also:
[System.Security.SecurityException: Request for the permission of type System.Security.Permissions.FileIOPermission, 
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.]

it seems that there is a Security.Permissions and memory issue when executing in Web.

Simply, my code:

         var schema = await JsonSchema4.FromTypeAsync<Person>();
         var json2 =schema.ToJson();	
        Console.WriteLine(json2);
 
I tested using Nuget Version NJsonSchema 8.11.6284.26855 and also old versions

I know that ToJson() inernally is using   JsonConvert.SerializeObject(JsonSchema4)

also , when i try to run:

         var json3  = JsonConvert.SerializeObject(schema)
It raises the same error.

The same code is working fine in PC in vs 2015 and consume abut 20MB in profiler.

Any ideas how can  I resolve it?
Thanks

**Comment by moh-hassan** [comment]
I tried to find the root of the problem, so start by minimizing memory needs by generating schema to Type int. The memory needed by dotnetfiddle become ~ 900KB ( less than the constraint 10 MB)
The test case location: [https://dotnetfiddle.net/G09QIe](https://dotnetfiddle.net/G09QIe)

I get the Exception and StackTrace  which is **System.Security.Permissions.FileIOPermission** :
The exception detail is:

			Exception type: System.Reflection.TargetInvocationException
			Message       : Exception has been thrown by the target of an invocation.
			Stacktrace:
			   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
			   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
			   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
			   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
			   at NJsonSchema.Infrastructure.ReflectionCache.PropertyOrField.GetValue(Object obj)
			   at NJsonSchema.JsonSchemaReferenceUtilities.UpdateSchemaReferencePaths(Object rootObject, Object obj, HashSet`1 checkedObjects)
			   at NJsonSchema.JsonSchema4.ToJson(JsonSchemaGeneratorSettings settings)
			   at Program.TestUsingTypedClass() in d:\Windows\Temp\x1c1itol.0.cs:line 25

			Exception type: System.Security.SecurityException
			Message       : Request for the permission of type 'System.Security.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.
			Stacktrace:
			   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
			   at System.Security.CodeAccessPermission.Demand()
			   at System.Reflection.RuntimeAssembly.VerifyCodeBaseDiscovery(String codeBase)
			   at System.Reflection.RuntimeAssembly.GetName(Boolean copiedName)
			   at NJsonSchema.JsonSchema4.get_ToolchainVersion()

I think that the assembly requires a privilege level granted by the System.Security.Permissions.FileIOPermission class.
Because the code is  running in a partial-trust context, the process might throw an exception due to insufficient privileges. 
Perhaps granting the code using Code Access Security may resolve the problem.
I didn't find line code number , so i can't spot where the problem is.

Any idea to resolve the security issue.
Thanks

**Comment by rsuter** [comment]
NJS uses reflection to access files and URLs if a JSON Schema references external schemas. This is where these calls come from...

**Comment by moh-hassan** [comment]
The code don't access external reference, simply it's:

        var schema =  JsonSchema4.FromTypeAsync<int>().Result;	
	    var json =schema.ToJson();	

Is giving the classes using the reflection Access  Code permission  can help in resolving this security issue.
Something like:

         [System.Security.Permissions.PermissionSet(System.Security.Permissions.SecurityAction.Assert, Unrestricted = true)]

**Comment by RSuter** [comment]
I don't think there is file access in this method, but could it be from heavy reflection usage (eg accessing private members)?

**Comment by moh-hassan** [comment]
I agree. Any way, this problem is only in dotnetfiddle.net site, but NJS is working fine in web application.

**Comment by RSuter** [comment]
Is it possible to reproduce this is a simple .net console app (ie started with partial trust)?

**Comment by moh-hassan** [comment]
I tried to run the sample [https://dotnetfiddle.net/Zs9R2u,](https://dotnetfiddle.net/Zs9R2u) but i can't load NJS library. It seems it's a limitation on the site. I tried to contact the support of dotnetfiddle.net , but no response from them.

**Comment by moh-hassan** [comment]
I modified the fiddle program: https://dotnetfiddle.net/Zs9R2u by using NJS  v9.5.4 and the error disappeared and there's no memory exception.

I can say that performance of NJS enhanced dramatically with the release 9.x
But there is another exception: 

> Json.NET version: Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
Run-time exception (line 14): One or more errors occurred.
>Stack Trace:
>[System.TypeLoadException: Could not load type 'Newtonsoft.Json.Serialization.SnakeCaseNamingStrategy' from assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.]
>[System.AggregateException: One or more errors occurred.]
  at Program.Main(): line 14

It seems that the release still use Newtonsoft.Json, Version=6.0.0.0 where SnakeCaseNamingStrategy is not available (it's in Newtonsoft.Json 9.0.1)

Kindly, can you package nuget  NJS with  Newtonsoft.Json, >9.0.1

**Comment by moh-hassan** [comment]
I'll close this issue becuase it's really fixed,  and open a new one with the new exception.

**Comment by RSuter** [comment]
I think you can just directly install the latest json.net and use its features with njs

**Comment by RSuter** [comment]
And yes, there were some major perf improvements in tojson()

**Comment by moh-hassan** [comment]
If I tried to install the latest json.net on fiddle.net with NJS, I get a compilation exception:

>Compilation error (line 0, col 0): An assembly with the same identity 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' has already been imported. Try removing one of the duplicate references.

**Comment by Spongman** [comment]
this is happening again. the code for `JsonSchema.ToolchainVersion` doesn't work in partial trust app domains:

[System.Security.SecurityException: Request for the permission of type 'System.Security.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.]
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessSecurityEngine.Check(CodeAccessPermission cap, StackCrawlMark& stackMark)
   at System.Security.CodeAccessPermission.Demand()
   at System.Reflection.RuntimeAssembly.VerifyCodeBaseDiscovery(String codeBase)
   at System.Reflection.RuntimeAssembly.GetName(Boolean copiedName)
   at System.Reflection.Assembly.GetName()
   at NJsonSchema.JsonSchema.get_ToolchainVersion()
