### ISSUE TITLE
Support for different NamingStrategy

### ISSUE THREAD

**Issue by lennygran** [RSuter/NJsonSchema#373]
Json.NET can serialize the same class with different outcome based on ContractResolver/NamingStrategy. Therefore even JsonProperty or DataMember attribute is declared on a property overriding its name, the JSON result may end up having original property name. It would be very useful if NJsonSchema supports different contract resolver similar way JSON.NET does it with serialization.

Otherwise the only option to generate correct schema with NJsonSchema is using the names declared by DataMember/JsonProperty attributes.

Essentially the desired behavior is to ignore DataMember/JsonProperty on class properties when generating schema, even though attributes present.

**Comment by rsuter** [comment]
In the future we will use contractresolver: https://github.com/NJsonSchema/NJsonSchema/issues/321

**Comment by rsuter** [comment]
Also see https://github.com/NJsonSchema/NJsonSchema/issues/370

**Comment by lennygran** [comment]
Great! Thank you.

**Comment by rsuter** [comment]
Can you test with the "netstandard" branch (clone repo, switch to netstandard branch and test in the demo project). This branch contains the "contractresolver" support. Is this issue handled when this branch is released?

**Comment by lennygran** [comment]
Works perfectly. Thank you for the change!
