### ISSUE TITLE
Generated C# will not compile

### ISSUE THREAD

**Issue by BeardedGnome** [rsuter/NJsonSchema#377]
I'm trialing using NJsonSchema to generate C# for glTF 2.0 (https://github.com/KhronosGroup/glTF/tree/2.0). Generating the code was easy enough, but it won't compile.

Here is the specific code:
`
    public partial class BufferView : int
    {
    }
`

And the errror:
`
Error	CS0509	'BufferView': cannot derive from sealed type 'int'
`

Any suggestions on what I can do to work around this?

**Comment by rsuter** [comment]
Can you post a link to the json schema?

**Comment by BeardedGnome** [comment]
https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0/schema

Here you go.

**Comment by rsuter** [comment]
Or can you post the original BufferView class/schema?

**Comment by BeardedGnome** [comment]
Root schema:
https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/glTF.schema.json

Buffer View:
https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/bufferView.schema.json

**Comment by BeardedGnome** [comment]
I think the issue is that glTF uses the index in the to JSON array to indicate which element. So other schemas (https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/accessor.schema.json) have a bufferView element that is just a number.

**Comment by rsuter** [comment]
Yes, it seems that this is the problem. The question is: Can this construct even be expressed with c#?

**Comment by rsuter** [comment]
The problem are these properties: 

    "buffer": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/KhronosGroup/glTF/2.0/specification/2.0/schema/glTFid.schema.json#/definitions/Json"
        }
      ],
      "description": "The index of the buffer."
    },

... which are handles as a reference instead of a simple reference.
I think this can be fixed without much effort.

**Comment by rsuter** [comment]
The latest commit adds support for allOf references which should fix your problem (the property is now of type "int"). You can clone the repo (branch: master) and implement your generator in the demo project to test with this fix... (or use the CI nuget feed). I suspect that you may have more issues with your schema, so please report if it is working now...

**Comment by BeardedGnome** [comment]
Thank you for the fast response. I need to step out, but will provide feedback shortly.

**Comment by BeardedGnome** [comment]
The generated code will compile. I still need to write something that uses it.

**Comment by rsuter** [comment]
Some base classes are still anonymously named (eg Json1, Json2, etc.)

**Comment by BeardedGnome** [comment]
I noticed that. I wasn't sure if that was intentional.

**Comment by BeardedGnome** [comment]
I've hit an exception in FromJson(string). Should I open another issue or is there a more efficient way?
