### ISSUE TITLE
incorrect Kind validation if the property is called "type"

### ISSUE THREAD

**Issue by camous** [RSuter/NJsonSchema#379]
I suspect a mixup in validation between json schema 'type' field and a possible field called 'type' within the schema itself.

**schema**
```json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "type" : {"type" : "integer"}
  }
}
```
**input**
```json
{
  "type": 1
}
```
**code**
```csharp
var schema = NJsonSchema.JsonSchema4.FromData(System.IO.File.ReadAllText("schema/opportunity.json"));
var errors = schema.Validate(System.IO.File.ReadAllText("input.json"));
foreach(var error in errors)
  Console.WriteLine(error.Property + "\t" + error.Kind);
```

**output**
```
type	StringExpected
```

**Comment by RSuter** [comment]
I cannot reproduce this problem (see referenced unit tests)... What version of NJS are you using?

**Comment by RSuter** [comment]
You need to use `JsonSchema4.FromJsonAsync()` here. `JsonSchema4.FromData()` generates a JSON Schema for the given JSON data....

**Comment by camous** [comment]
indeed, mixed up between FromData & FromJsonAsync. thanks !
