### ISSUE TITLE
sample code results in exception

### ISSUE THREAD

**Issue by tdjastrzebski** [RSuter/NJsonSchema#380]
The sample code at [(sample)](https://github.com/RSuter/NJsonSchema#njsonschemacodegeneration-usage) results in ArgumentNullException when trying to use reference schema.
```
var schema = JsonSchema4.FromUrlAsync("http://petstore.swagger.io/v2/swagger.json").GetAwaiter().GetResult();
var generator = new CSharpGenerator(schema);
var file = generator.GenerateFile();
```
It seems like the provided example is incomplete.

**Comment by RSuter** [comment]
A swagger spec is not a JSON Schema, but it uses JSON Schemas to describe DTOs... To read a swagger spec, use the classes from http://NSwag.org: 

     SwaggerDocument.FromUrlAsync("http://petstore.swagger.io/v2/swagger.json")

**Comment by tdjastrzebski** [comment]
My point was the published sample code did not work.

**Comment by RSuter** [comment]
I don't know of a sample in NJS where a swagger spec is loaded as JSON Schema - this is not possible, because it is not a JSON Schema... 

    new CSharpGenerator(schema);

... takes a JSON Schema object and not a SwaggerDocument.

**Comment by tdjastrzebski** [comment]
IC
Thanks
