### ISSUE TITLE
Method not found: JsonObjectTypeDescription.FromType

### ISSUE THREAD

**Issue by LeonidEfremov** [RSuter/NJsonSchema#383]
After upgrade NJsonSchema to 9.1.0 got exception below (NSwag.SwaggerGeneration.WebApi 10.6.6324.28500).

```
A first chance exception of type 'System.MissingMethodException' occurred in mscorlib.dll

Additional information: Method not found: 'NJsonSchema.Generation.JsonObjectTypeDescription NJsonSchema.Generation.JsonObjectTypeDescription.FromType(System.Type, System.Collections.Generic.IEnumerable`1<System.Attribute>, NJsonSchema.EnumHandling)'.
```

**Comment by RSuter** [comment]
NSwag v10.6 is not compatible with NJsonSchema v9.1... you need to install NJS v8.x. NJS v9.x will be used by the next version of NSwag (v11)

**Comment by LeonidEfremov** [comment]
Oh, i see, thanx!

**Comment by RSuter** [comment]
NJS v9.1 is .NET Standard library and I have to also migrate NSwag to .NET Standard. I hope this work is done soon, but the NSwag project has lots of projects to migrate...

**Comment by LeonidEfremov** [comment]
I think now you get tons messages about that, because nuget NSwag.SwaggerGeneration.WebApi have dependency NJsonSchema >= 8.33.6323.36213.

**Comment by RSuter** [comment]
It should not, because NuGet will install the lowest possible version of a dependency... But yes, the new version of NSwag should be released soon.

**Comment by LeonidEfremov** [comment]
@RSuter now i just update nuget packages in my project in MSVS... and get new incompatible version of NJsonSchema.

**Comment by RSuter** [comment]
Yes, this is because you use the "old" NuGet where every dependency (not only direct ones) are shown. In the new NuGet version (v4) you only see direct dependencies and this works... If you just upgrade the NSwag packages, you should not have any problems

**Comment by LeonidEfremov** [comment]
@RSuter thank you for explanation, will do that.
