### ISSUE TITLE
NullReferenceException when trying to deserialize SwaggerDocument

### ISSUE THREAD

**Issue by moezubair** [RSuter/NJsonSchema#385]
I am getting an exception when I try to deserialize a swagger.json document:
```
An exception of type 'System.NullReferenceException' occurred in NJsonSchema.dll but was not handled in user code

Additional information: Object reference not set to an instance of an object.

If there is a handler for this exception, the program may be safely continued.
```

The Swagger doc is attached

[swagger1.json.txt](https://github.com/RSuter/NJsonSchema/files/1012644/swagger1.json.txt)

The error occurs at:
```
                 private SwaggerDocument service = new SwaggerDocument();
                service = JsonConvert.DeserializeObject<SwaggerDocument>(msg);
```

msg is the content of the swagger.json

This error occurs only in the document attached, some swagger documents work fine.

**Comment by RSuter** [comment]
Use `service.ToJson()`
