### ISSUE TITLE
Title property on items

### ISSUE THREAD

**Issue by Julien2017** [RSuter/NJsonSchema#387]
Hello there,

Tank you very much for your library, it was very useful coupled with http://jeremydorn.com/json-editor/.
Still i have a minor issue, i need the items property to have a title property.

What i have today is something like this 
![slideritem](https://cloud.githubusercontent.com/assets/28904301/26370655/c035a6e2-3ff8-11e7-8924-daabbe25bb2b.PNG)

I need it to be like this
![slidertitle](https://cloud.githubusercontent.com/assets/28904301/26370739/0404d618-3ff9-11e7-9728-0fd133cb535a.PNG)

I understood i have to add the "title" property to the items, but i have no idea on how to do it properly and i dont want to mess around with manual insertion.
[json-schema.txt](https://github.com/RSuter/NJsonSchema/files/1023391/json-schema.txt)

What attribute should i use to put the title on the collection of objects ? DisplayName is not picked by njsonschema and Display attribute is not applicable to classes.

**Comment by Julien2017** [comment]
Hey just found what i needed on the doc here : 
https://github.com/RSuter/NJsonSchema/wiki/Custom-Schema-Properties

**Comment by RSuter** [comment]
Also try the DescriptionAttribute

https://msdn.microsoft.com/en-us/library/system.componentmodel.descriptionattribute(v=vs.110).aspx
