### ISSUE TITLE
Hard crash when ShouldSerialize method uses this

### ISSUE THREAD

**Issue by LordJZ** [RSuter/NJsonSchema#395]
#329 added ShouldSerialize call on a null instance, causing a hard exception for classes like this:

````
class A {
public int P { get; set; }
public bool ShouldSerializeP() {
    return P != 10;
}
}
````

**Comment by RSuter** [comment]
https://github.com/RSuter/NJsonSchema/blob/a6c663a2839c4278bc992876e573b2d4070b28d7/src/NJsonSchema/Generation/JsonSchemaGenerator.cs#L311

**Comment by RSuter** [comment]
Exceptions are now ignored... ShouldSerialize is a runtime feature and cannot be used by NJS when an instance is needed...

**Comment by RSuter** [comment]
Fixed in NSwag: https://github.com/NSwag/NSwag/commit/189727514720861bbdd03c241efc7aae22d8991f

**Comment by LordJZ** [comment]
Thanks @RSuter! Super fast responses as always!
