### ISSUE TITLE
How to resolve 'Model' reference in t4 template?

### ISSUE THREAD

**Issue by gzak** [RSuter/NJsonSchema#404]
I've been trying to write my own customized template for the C# class generator, and I was able to get the error messages down to just the 'Model' reference - but I can't for the life of me seem to figure out how to get it to resolve within the template. Is there something special I need to do to get it working?

Worth mentioning: I hadn't done any template customization yet, I just pasted the original and was trying to get it to work.

**Comment by RSuter** [comment]
you also need the partial class (*.extension.cs) for each .tt file..

**Comment by gzak** [comment]
I added that to, but for some reason it wasn't detecting it. I couldn't get it to "bind" to the extension class and inherit its properties the was an aspx page binds to its codebehind file.

**Comment by RSuter** [comment]
You have to check that the namespace and class name exactly matches the T4 class' name and that the T4 custom tool is set to "TextTemplatingFilePreprocessor"

**Comment by RSuter** [comment]
BTW: I am planning to switch the template engine (T4) and use DotLiquid instead in the future... This way customizations are much easier to do (ie. define a directory with template replacements)

**Comment by RSuter** [comment]
New template engine: https://github.com/RSuter/NJsonSchema/wiki/Templates
