### ISSUE TITLE
C# code can be generated with C# keywords

### ISSUE THREAD

**Issue by DoctorInsano** [RSuter/NJsonSchema#417]
I've got a gigantic schema (not created by me) (https://gist.github.com/DoctorInsano/bbb0e087a35a2c303449767db84ae3ca) that causes NJsonSchema to crash when turning it into a file (issue stems from ConvertToUpperCamelCase in ConversionUtilities). 

But even with that fixed, the generated file uses C# keywords for property names.

**Comment by RSuter** [comment]
Can you post a simple repro sample for the problem?

**Comment by DoctorInsano** [comment]
Certainly. Sorry about that. I've updated the gist. It seems that having any property with a C# keyword will generate a C# property with that keyword as the property name.

**Comment by RSuter** [comment]
The property should be generated as Default... Do you have a sample schema?

**Comment by DoctorInsano** [comment]
```
{
    "type": "object",
    "properties": {
        "meta": {
            "properties": {
                "lastSchemaUpdate": {
                    "default": 0,
                }
            }
        }
    }
}
```

**Comment by DoctorInsano** [comment]
Oh, wait, this is my fault. The schema I was provided was bad. Sorry about that.
