### ISSUE TITLE
Optional fields -  | null/undefined

### ISSUE THREAD

**Issue by Paul183425** [RSuter/NJsonSchema#420]
Is there any reason why adding  ' | null/undefined' to the TypeScript output is necessary for optional fields.

With the example below, Login and Password have a Required DataAnnotation and so output as you would expect, but the ServiceAccountId and EnvironmentId have not DataAnnotations and add the ' | null' on the end.

export interface AdServiceAccountModel {
    Login: string;
    Password: string;
    ServiceAccountId?: number | null;
    EnvironmentId?: number | null;
}

The output I would have expected is:

export interface AdServiceAccountModel {
    Login: string;
    Password: string;
    ServiceAccountId?: number;
    EnvironmentId?: number;
}

Is this changeable? Or there for a reason?

Many thanks,

Paul

**Comment by RSuter** [comment]
This is needed if strictNullChecks is enabled in tsconfig... But in your case you can change the NullValue to TypeScriptNullValue.Undefined so that

    ServiceAccountId?: number | undefined;

is generated... If you select TypeScript 1.8 as TypeScriptVersion then this "| undefined" is not generated...

**Comment by Paul183425** [comment]
OK. Thank you for your reply.

**Comment by RSuter** [comment]
Can we close this? Or do you have problems with this?

**Comment by Paul183425** [comment]
Yes. Sorry, it can close now.

Thanks.
