### ISSUE TITLE
Is JsonSchema4.FromData implemented?

### ISSUE THREAD

**Issue by realisable** [RSuter/NJsonSchema#422]
Having tried several different valid JSON files, the best this method seems to do is to parse the top most properties; all nested properties are ignored. My question is this by design, a limitation, or a bug?

**Comment by realisable** [comment]
Cancel this.

**Comment by RSuter** [comment]
See https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/DataToJsonSchemaGenerator.cs

**Comment by realisable** [comment]
Many Thanks, have finally worked things out.
