### ISSUE TITLE
Feature Request: Optionally Ignore Data Members Having the Obsolete Attribute

### ISSUE THREAD

**Issue by dagrooms52** [RSuter/NJsonSchema#424]
I would like to optionally ignore data members of my schema that have been tagged with the Obsolete attribute. I would like to specify the option to ignore these data members in the `JsonSchemaGeneratorSettings` object that is injected into the `JsonSchemaGenerator` object upon construction. 

This issue is just to make note before I PR these changes to the repo. Besides the necessary changes to the `JsonSchemaGeneratorSettings` class, the functional change would be in [this method](https://github.com/RSuter/NJsonSchema/blob/6c0f66e896616cadf1ac46bdbbf3a02f3f46d0e0/src/NJsonSchema/Generation/JsonSchemaGenerator.cs#L627) to check for the ObsoleteAttribute type in the type's attribute collection.

Further changes may be required to ignore classes having the Obsolete attribute, but I have not researched the changes necessary to implement this functionality.

**Comment by RSuter** [comment]
Maybe we should add the option PropertyIgnoreAttributes: string[] (array of full type names) so that you can specify any attributes to exclude properties. 

I'm not sure whether exclusion of classes makes sense - should they be then just be treated as any?

**Comment by dagrooms52** [comment]
I considered a list of attributes that would cause properties to be ignored in the final schema; however, how many properties really make sense to be in that list? That would let consumers of this API add anything, such as the `DataMember` attribute for example, and when used incorrectly would lead to a lot of confusion.

When my organization deprecates a class but leaves it in the dll, the consumers would no longer like to be able to see the class in the Json Schema, so one way or another we will be removing it from the final result.

**Comment by RSuter** [comment]
https://github.com/RSuter/NJsonSchema/commit/044d109e58f9ba1318a676b852a2349592e2ee33
