### ISSUE TITLE
C# interface to TypeScript class/interface not generating properties

### ISSUE THREAD

**Issue by tdamir** [RSuter/NJsonSchema#428]
The interface properties are not generated anymore on TypeScript interface.
````
            var schema = await JsonSchema4.FromTypeAsync<IPerson>();
            var schemaData = schema.ToJson();

            Console.WriteLine(schemaData);
````
````
        public interface IPerson
        {
            string Name { get; set; }
        }
````
Output:
````
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "IPerson",
  "type": "object",
  "additionalProperties": false
}
````

**Comment by tdamir** [comment]
I just noticed that there is a new option for generator (GenerateAbstractProperties). I apologize.

**Comment by tdamir** [comment]
I have following use case: 
````
public interface INode {
 string NodeType {get;}
}

public class Node1 : INode {
[DefaultValue('node1')]
string NodeType {get;} = 'node1';
}

public class Node2 : INode {
[DefaultValue('node2')]
string NodeType {get;} = 'node2';
}

public class NodeModel {
List<INode> Nodes {get; set; }
}
````

This way I can use the generated classes (Node1, Node2) from TS app to send the values back to the server without setting the NodeType value (since default value is generated in class). On server side I can use JsonInheritanceConverter or custom JsonConverter to convert the nodes back to specific type (by examination of nodeType property).

Unfortunately this scenario is not working because I'm getting 'System.InvalidOperationException: The JSON property 'nodeType' is defined multiple times on type 'xxx'. Actually I'm getting this when generating the ApiController proxy using NSwag but the error is thrown on JsonSchemaGenerator.LoadPropertyOrFieldAsync function.

It would be nice if something like following is generated in this case:
````
interface INode {
nodeType: string;
}

class Node1 implements INode { // not important to implement the interface
nodeType: string = 'node1';
}

class Node2 implements INode { // not important to implement the interface
nodeType: string = 'node2';
}
````

Do you have any idea how to handle this scenario?

**Comment by tdamir** [comment]
My bad. I totally misunderstood the use of JsonInheritanceConverter and inheritance. Now the scenario described above is working as expected. I apologize again.

**Comment by RSuter** [comment]
Maybe we should add a sample to the docs or make it more clear?

**Comment by tdamir** [comment]
I think the doc about inheritance is fine - It's just me not paying attention more carefully. I was under impression that we can manually control the discriminator values using DefaultValue attribute but that is not the case. The builtin inheritance handling is implemented in the way to act transparently (i.e discriminator property is not supposed to be defined explicitly on the base type) and possible discriminator values are hard coded (i.e.: resolved by type name).
