### ISSUE TITLE
TypeScript generation: Discriminator name in ClassTemplate and JsonInheritanceConverter mismatch

### ISSUE THREAD

**Issue by tdamir** [RSuter/NJsonSchema#430]
Discriminator name (property name) should match the one defined in JsonInheritanceConverter.
JsonInheritanceConverter defines 'discriminator' and ClassTemplate.tt '_discriminator'.

CSharp generation is correct because ClassTemplateModel contains Discriminator property which holds the name of the discriminator property and is usable from t4 template.

Maybe the properties regarding the inheritance info should be moved to the ClassTemplateModelBase?

**Comment by RSuter** [comment]
Can you create a PR with a fix? (Just commit the .tt files, not the generated ones...)

**Comment by tdamir** [comment]
The problem is when we send back the instance of the class to the server, it will not contain the specified discriminator (because it is hard coded in .tt file: '_discriminator') and JsonInheritanceConverter is expecting it when deserializing.

Lets say we have a JsonInheritanceConverter with discriminator 'name'
When deserializing, it will use a property 'name' for deciding what type to create.

````
    public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
    {
      JObject jObject = serializer.Deserialize<JObject>(reader);
      string discriminator = Extensions.Value<string>((IEnumerable<JToken>) jObject.GetValue(this._discriminator));
````

This is what is generated in class: 
````
export class Animal implements IAnimal {

    protected _discriminator: string; // property name should be a 'name'
````

I would gladly create a PR with fix, but unfortunately I have only vs2015 installed and it can't open the projects. I'm delaying the installation of vs2017 for some time but maybe this is the time to try it - I have a valid reason at least...

**Comment by RSuter** [comment]
Each ts class has a toJSON method which converts the property back to the correct field... Stringify should call this tojoson method so that it is correctly serialized

**Comment by tdamir** [comment]
Oh, my bad. I have customized ClassTemplate and removed toJSON() method some time ago because I had some issues with it, I cannot recall what kind. I just regenerated the classes with toJSON() method and clicked around on the app and it looks okay. This is totally my fault - sorry! I'll try to be more careful in the future.
