### ISSUE TITLE
StringEnumConverter attribute not generated for nullable enums

### ISSUE THREAD

**Issue by opus131** [RSuter/NJsonSchema#446]
Our datamodel has nullable and not-nullable enum fields.

The enum definitions are correctly generated like this:

```c#
public enum Currency
{
  [System.Runtime.Serialization.EnumMember(Value = "EUR")]
  EUR = 0,

  [System.Runtime.Serialization.EnumMember(Value = "GBP")]
  GBP = 1,

  [System.Runtime.Serialization.EnumMember(Value = "USD")]
  USD = 2
}

public enum Gender
{
  [System.Runtime.Serialization.EnumMember(Value = "Male")]
  Male = 0,

  [System.Runtime.Serialization.EnumMember(Value = "Female")]
  Female = 1,
}
```

However, the data model is generated like this:

```c#
[Newtonsoft.Json.JsonProperty("currency", Required = Newtonsoft.Json.Required.Always)]
[Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
public Status Currency { get; set; }

[Newtonsoft.Json.JsonProperty("gender", Required = Newtonsoft.Json.Required.AllowNull)]
public Gender? BounceType { get; set; }
```

Apparently the `StringEnumConverter` attribute is not being generated for nullable fields.

Any ideas?

**Comment by RSuter** [comment]
This is a bug...

**Comment by RSuter** [comment]
Cannot reproduce, see unit test in commit

**Comment by opus131** [comment]
Hmm, we are using NJsonSchema version 8.5.6255.20253 
Could  it be that this has been fixed in a newer version?

**Comment by RSuter** [comment]
Yes, this is must be it...

**Comment by RSuter** [comment]
Have you tried with the latest version?

**Comment by opus131** [comment]
Apologies - I thought that since your unit test proved that the issue is fixed in the latest version, you'd just close the issue.
Unfortunately we are currently tied to using 8.5.6255.20253. We have worked around the problem, and I have no easy way to test our specific setup with a different version of NJsonSchema.

Thank you for following up though!

**Comment by RSuter** [comment]
Ok thanks for your reply. What is stopping you from upgrading?

**Comment by opus131** [comment]
@RSuter it used in a part of our toolchain that we do not directly control...
