### ISSUE TITLE
validating raw Json against Json schema generated from C# interfaces

### ISSUE THREAD

**Issue by tomschreck** [RSuter/NJsonSchema#467]
I'm using NJsonSchema to validate raw Json strings against a JsonSchema generated from a .Net type.  The .Net type is an interface containing a child property that's also an interface.  

Here's my interface:

    public interface IPersonDataContract
	{
		Int32 PersonId { get; set; }
		String FirstName { get; set; }
		String LastName { get; set; }
		String Name { get; set; }
		DateTime? Birthday { get; set; }
		Int32 Age { get; }
		IEnumerable<IPhoneNumberDataContract> PhoneNumberList { get; set; }
	}

Here's the interface describing an item in the PhoneNumberList property:

    public interface IPhoneNumberDataContract
	{
		Int32 PhoneNumberTypeId { get; set; }
		String PhoneNumberTypeName { get; set; }
		String PhoneNumber { get; set; }
	}

I'm using NJsonSchema to validate raw Json serialized from a PersonDataContract instance (PersonDataContract implements IPersonDataContract) against the JsonSchema generated from IPersonDataContract.  I'm receiving validation errors because PhoneNumberList is defined as an interface (IEnumerable of IPhoneNumberDataContract).  If I change the definition of PhoneNumberList to a concrete class (IEnumerable of PhoneNumberDataContract), then no errors are produced through validation.

Here's the JsonSchema generated from IPersonDataContract with IPhoneDataContract:

    
	{
		"$schema": "http://json-schema.org/draft-04/schema#",
		"title": "IListOfPersonDataContract",
		"type": "array",
		"items": {
			"$ref": "#/definitions/PersonDataContract"
		},
		"definitions": {
			"PersonDataContract": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					//removed for brevity
				}
			},
			"IPhoneNumberDataContract": {
				"type": "object",
				"additionalProperties": false
			}
		}
	}

Here's the JsonSchema generated from IPersonDataContract with PhoneDataContract (a concrete class):
    

	{
		"$schema": "http://json-schema.org/draft-04/schema#",
		"title": "IListOfPersonDataContract",
		"type": "array",
		"items": {
			"$ref": "#/definitions/PersonDataContract"
		},
		"definitions": {
			"PersonDataContract": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					//removed for brevity
				}
			},
			"PhoneNumberDataContract": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"PhoneNumberTypeId": {
						"type": "integer",
						"format": "int32"
					},
					"PhoneNumberTypeName": {
						"type": [
							"null",
							"string"
						]
					},
					"PhoneNumber": {
						"type": [
							"null",
							"string"
						]
					}
				}
			}
		}
	}

The difference is the JsonSchema built from a concrete class (PhoneNumberDataContract) includes the additional properties whereas the JsonSchema from an interface excludes the additional properties.  My raw Json validates when using the JsonSchema based on concrete class.  

I do not understand why this is happening because interfaces includes the necessary property definitions.  How do you make JsonSchema include properties when dealing with interfaces?  It seems to me that since interfaces describe what a concrete class contains, then JsonSchema generated from an interface should easily include the properties of an interface since a concrete class, based on an interface, must implement the interface's signature.

I'm not able to define my interfaces with concrete classes because I'm using a code generator that takes an interface and generates the concrete classes.

Thanks for your help.

**Comment by RSuter** [comment]
Try

https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/JsonSchemaGeneratorSettings.cs#L40

**Comment by tomschreck** [comment]
Thanks for the reply.  That fixed my issue.  Here's my implementation in case anyone else has this problem:		

	[TestMethod()]
	public async Task TestValidateRawJsonAgainstJsonSchemaAsync()
	{
		IEnumerable<PersonDataContract> personList = repository.GetPersonList();

		var rawJson = JsonConvert.SerializeObject(personList);
		var jsonSchema4 = await GetJsonSchemaFromType<IEnumerable<PersonDataContract>>();
		var schemaData = jsonSchema4.ToJson();
		var errors = jsonSchema4.Validate(rawJson);

		Assert.IsNotNull(errors);
	}

	private async Task<JsonSchema4> GetJsonSchemaFromType<T>()
	{
		var settings = new JsonSchemaGeneratorSettings { GenerateAbstractProperties = true };
		return await JsonSchema4.FromTypeAsync<T>(settings);
	}

Out of curiosity, how come GenerateAbstractProperties defaults to false?  It seems to me that it should default to true so creating  JsonSchema is friction-less for use cases where interface/abstract are involved.

Thanks for your help.

**Comment by RSuter** [comment]
The problems:

1. We use newtonsoft.json contracts internally to iterate properties, the setting just causes a fallback to regular reflection
2. The main problem with this setting is that some properties may be defined multiple times (eg when using inheritance) which may cause other problems

**Comment by RSuter** [comment]
Maybe we need some more magic for this:

E.g. generate interface props if the interface is used alone (no instances in the graph) and only generate props when not already in a base type... but im sure there are lots of edge cases for this
