### ISSUE TITLE
FlattenInheritanceHierarchy not working with parent interface

### ISSUE THREAD

**Issue by tomschreck** [RSuter/NJsonSchema#468]
Hello.  I'm working with different settings available in JsonSchemaGeneratorSettings.  I've constructed a scenario where my interface extends another interface like so:

	public interface IPersonDataContract : IMessage
	{
		Int32 PersonId { get; set; }
		String FirstName { get; set; }
		String LastName { get; set; }
		String Name { get; set; }
		DateTime? Birthday { get; set; }
		Int32 Age { get; }
		IEnumerable<IPhoneNumberDataContract> PhoneNumberList { get; set; }
	}
	public interface IMessage
	{
		String MessageBody { get; set; }
	}

The concrete PersonDataContract has a MessageBody property to fulfill the signature expressed by IPersonDataContract. 

When attempting to validate raw Json against a list of IPersonDataContract, the validation is failing on MessageBody which does not exist in JsonSchema.

	[TestMethod()]
	public async Task TestGenerateSchemaModelFromTypeAsync()
	{
		//ASSEMBLE
		IEnumerable<IPersonDataContract> personList = repository .GetPersonList();

		var json = JsonConvert.SerializeObject(personList);

		//ACT
		var isValid = await IsJsonValidAgainstType<IEnumerable<IPersonDataContract>>(json);
			
		//ASSESS			
		Assert.IsTrue(isValid);
	}

	private async Task<Boolean> IsJsonValidAgainstType<T>(String json)
	{
		var settings = new JsonSchemaGeneratorSettings { GenerateAbstractProperties = true, FlattenInheritanceHierarchy = true};
		var jsonSchema4 = await JsonSchema4.FromTypeAsync<T>(settings); ;
		var schemaData = jsonSchema4.ToJson();
		var errors = jsonSchema4.Validate(json);

		return (errors.Count == 0);
	}

Here's the generated JsonSchema4 schema for IEnumerable of IPersonDataContract:

	{
	  "$schema": "http://json-schema.org/draft-04/schema#",
	  "title": "IEnumerableOfIPersonDataContract",
	  "type": "array",
	  "items": {
		"$ref": "#/definitions/IPersonDataContract"
	  },
	  "definitions": {
		"IPersonDataContract": {
		  "type": "object",
		  "additionalProperties": false,
		  "properties": {
			"Age": {
			  "type": "integer",
			  "format": "int32"
			},
			"PersonId": {
			  "type": "integer",
			  "format": "int32"
			},
			"FirstName": {
			  "type": [
				"null",
				"string"
			  ]
			},
			"LastName": {
			  "type": [
				"null",
				"string"
			  ]
			},
			"Name": {
			  "type": [
				"null",
				"string"
			  ]
			},
			"Birthday": {
			  "type": [
				"null",
				"string"
			  ],
			  "format": "date-time"
			},
			"PhoneNumberList": {
			  "type": [
				"array",
				"null"
			  ],
			  "items": {
				"$ref": "#/definitions/IPhoneNumberDataContract"
			  }
			}
		  }
		},
		"IPhoneNumberDataContract": {
		  "type": "object",
		  "additionalProperties": false,
		  "properties": {
			"PhoneNumberTypeId": {
			  "type": "integer",
			  "format": "int32"
			},
			"PhoneNumberTypeName": {
			  "type": [
				"null",
				"string"
			  ]
			},
			"PhoneNumber": {
			  "type": [
				"null",
				"string"
			  ]
			}
		  }
		}
	  }
	}

My JsonSchemaGeneratorSettings support GenerateAbstractProperties and FlattenInheritanceHierarchy.  I'm expecting the properties from IMessage to be flattened into properties from IPersonDataContract, however, that's not happening.

Am I misunderstanding FlattenInheritanceHierarchy?

Thanks for your help.

**Comment by RSuter** [comment]
Yes this is how it should work. But i think base interfaces are not supported yet.

**Comment by tomschreck** [comment]
Do you know when this bug will be fixed?

**Comment by RSuter** [comment]
This is a special case when GenerateAbstractProperties and FlattenInheritanceHierarchy are set. I dont use these settings often so i didnt even think of this scenario... im currently working on some refactorings, maybe after that i can look into it.

**Comment by tomschreck** [comment]
Thank you very much for looking into this use case.

**Comment by RSuter** [comment]
If possible, please add more unit tests to: 

https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.Tests/Generation/FlattenInheritanceHierarchyTests.cs

with a PR
