### ISSUE TITLE
Exception error: [System.TypeLoadException: Could not load type 'Newtonsoft.Json.Serialization.SnakeCaseNamingStrategy' from assembly 'Newtonsoft.Json, Version=6.0.0.0

### ISSUE THREAD

**Issue by moh-hassan** [RSuter/NJsonSchema#469]
I modified the fiddle program: https://dotnetfiddle.net/Zs9R2u by using NJS v9.5.4.

I can say that the Memory performance of NJS enhanced dramatically with the release 9.x
There is an exception:

    Json.NET version: Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
    Run-time exception (line 14): One or more errors occurred.
    Stack Trace:
    [System.TypeLoadException: Could not load type 'Newtonsoft.Json.Serialization.SnakeCaseNamingStrategy' from assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.]
    [System.AggregateException: One or more errors occurred.]
    at Program.Main(): line 14

It seems that the release still use Newtonsoft.Json, Version=6.0.0.0 where SnakeCaseNamingStrategy is not available (it's in Newtonsoft.Json 9.0.1)

Kindly, can you package nuget NJS with Newtonsoft.Json, >9.0.1

**Comment by RSuter** [comment]
NJS already uses Json.NET 9.0.1: https://www.nuget.org/packages/NJsonSchema/

Where is this exception coming from?

**Comment by moh-hassan** [comment]
The exception is coming when executing NJS from within dotnetfiddle, you can check it online https://dotnetfiddle.net/Zs9R2u

**Comment by RSuter** [comment]
I saw it, but when i install just json.net latest and dont use njs it still shows v6?

**Comment by moh-hassan** [comment]
I posted a message to fiddle team support. I think the problem may be related to fiddle when loading dependent assemblies.

**Comment by RSuter** [comment]
It seems as Newtonsoft.Json 6 is preinstalled and cannot be changed: 

https://dotnetfiddle.net/iqPYBn

**Comment by RSuter** [comment]
https://dotnetfiddle.uservoice.com/forums/228764--net-fiddle-ideas/suggestions/10782315-load-the-specified-version-of-json-net-rather-than

**Comment by RSuter** [comment]
Indeed, it would be nice if we could use dotnetfiddle for some demos/samples in the NJS wiki/frontpage...

**Comment by moh-hassan** [comment]
I voted at https://dotnetfiddle.uservoice.com/forums/228764--net-fiddle-ideas/suggestions/10782315-load-the-specified-version-of-json-net-rather-than , 3 times :)  to get this feature.

**Comment by RSuter** [comment]
Please update this issue as soon as you hear something from dotnetfiddle...

**Comment by moh-hassan** [comment]
OK, I'm waiting dotnetfiddle response and I'll feedback .

**Comment by moh-hassan** [comment]
>Please update this issue as soon as you hear something from dotnetfiddle..
**Now dotnetfiddle  is updated with Newtonsoft.Json, Version=10.0.0.0**
and No exception is fired :)
My [fiddle program: ](https://dotnetfiddle.net/Zs9R2u   is working fine
My issue is resolved.
)

**Comment by RSuter** [comment]
Ah nice, thanks for the update.
