### ISSUE TITLE
Can I create a schema for a typed DataTable?

### ISSUE THREAD

**Issue by moh-hassan** [RSuter/NJsonSchema#470]
I try to create schema for a typed DataTable using this code:

            DataTable dt = new DataTable("table1");
            dt.Columns.Add("id", typeof(int));
            dt.Columns.Add("location", typeof(byte[]));
           
            Type mydt = dt.GetType();           
            var schema = await JsonSchema4.FromTypeAsync(mydt); // it raise an exception
            Console.WriteLine(schema.ToJson());
			
I get the exception error:

>System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The JSON property 'Item' is defined multiple times on type 'System.Data.DataRelationCollection'.

Do njs support typed DataTable?

**Comment by RSuter** [comment]
No this is not supported as it cannot be generated via reflection

**Comment by RSuter** [comment]
You have to manually build up the schema based on the columns... just create a NJS schema resolver, and schema generator and build the schema with that...

**Comment by moh-hassan** [comment]
I tried schema resolver, but it can't help , bez the resolver see DataTable as The JSON property 'Item' which is defined multiple times on type 'System.Data.DataRelationCollection'.

Only, the following methods are called by resolver and fire the same exception:
JsonContract CreateContract(Type objectType)
JsonArrayContract CreateArrayContract(Type objectType)

The other methods are not called.

My workaround solution, is creating POCO class for the datatable and then generating schema for POCO class.
I deserialize DataTable as List<POCO>.

**Comment by RSuter** [comment]
Something like
```
var resolver = new JsonSchemaResolver();
var generator = new JsonSchemaGenerator(settings);
var schema = new JsonSchema4();
schema.Type = Object; 
schema.Properties["Id"] = await generator.GenerateAsync<JsonProperty>(typeof(int), resolver);
...
```

**Comment by moh-hassan** [comment]
Thanks for code.
I used it and created a schema like:

      {
 	"$schema": "http://json-schema.org/draft-04/schema#",
 	"type": "object",
 	"properties": {
 		"Id": {
 			"type": "integer",
 			"format": "int32"
 		},
 		"location": {
 			"type": "string",
 			"format": "byte"
 		}
 	}
 }

DataTable is considered as an array of objects. I will modify the code to get it.
Thanks for help.
