### ISSUE TITLE
Need for a JsonSchema4.FromSchemaData function

### ISSUE THREAD

**Issue by OlivierSohn** [RSuter/NJsonSchema#483]
Currently there is :
- a function to do `jsonSchemaAsFile -> jsonSchema` : `JsonSchema4.FromFileAsync` 
- a function to do `jsonAsData -> jsonSchema` : `JsonSchema4.FromData`
- but there is no function to do `jsonSchemaAsData -> jsonSchema` (we could name it `JsonSchema4.FromSchemaData`).

My usecase is that I embed schema files as resources and want to generate the code from the resources.

Has anyone some guidelines on how to implement it? I'm willing to try implementing it and submitting a patch.

Thanks!

**Comment by RSuter** [comment]
I think its FromJsonAsync what you are looking for...

**Comment by RSuter** [comment]
FromFileAsync => Input: JSON Schema in file
FromJsonAsync => Input: JSON Schema as string
FromData => Input: Sample data which is converted to JSON Schema

**Comment by OlivierSohn** [comment]
ok thanks very much for your help! I'll close the issue as `FromJsonAsync` perfectly fits my initial need .
