### ISSUE TITLE
What is the proper way to use FromJSONAsync when the schema has references?

### ISSUE THREAD

**Issue by OlivierSohn** [RSuter/NJsonSchema#484]
Hello,
I'm struggling with this: I have 2 schema files embedded as dotnet resources, and one schema is referencing the other:

`BooleanMemberEvent` content (available as embedded resource):
```json
{
  "type":"object",
  "additionalProperties": false,
  "properties": {
    "time": {
      "type": "string"
    },
    "memberSource": {
      "$ref": "MemberSource"
    },
    "value": {
      "type": "boolean"
    }
  }
}
```
`MemberSource` content (available as embedded resource):
```json
{
  "type":"object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "integer"
    },
    "device": {
      "type": "string"
    },
    "ip": {
      "type": "string"
    }
  }
}
```
I'd like to use FromJSONAsync on both resources to generate the csharp code of the types they define.

I wrote the code below, but during the task `FromJsonAsync` I encounter the error: `Could not resolve the JSON path 'MemberSource' because no document path is available.`

Looking at the source I saw that it is be because I pass null as 2nd parameter of the constructor of `CSharpTypeResolver`. How should I construct the object passed here ? I saw in `CSharpGenerator` constructors that by default the schema is passed here. Should I create a schema containing all other schemas? How can I do that?

Many thanks for your help!

```csharp

    class Program
    {
        static internal string outputDir = "../generated/dotnet/";
        static internal string inputDir = "../jsonschema/";

        static internal CSharpTypeResolver resolver = new CSharpTypeResolver(new CSharpGeneratorSettings(), null);

        static void Main(string[] args)
        {
            IDictionary<string, JsonSchema4> generators = new Dictionary<string, JsonSchema4>();

            Assembly thisExe = typeof(Program).GetTypeInfo().Assembly;
            foreach (string name in thisExe.GetManifestResourceNames())
            {
                JsonSchema4 schema = resourceToSchema(name);
                generators.Add(name, schema);
            }
            resolver.AddGenerators(generators);
            foreach (KeyValuePair<string, JsonSchema4> pair in generators)
            {
                var name = pair.Key;
                var schema = pair.Value;
                string code = schemaToCode(schema);
                writeGeneratedSource(name, code);
            }
        }

        private static string schemaToCode(JsonSchema4 schema) {
            var generator = new CSharpGenerator(schema, new CSharpGeneratorSettings(), resolver, new object());
            return generator.GenerateFile("");
        }

        private static JsonSchema4 resourceToSchema(string resourceName)
        {
            Assembly assembly = typeof(Program).GetTypeInfo().Assembly;

            using (Stream stream = assembly.GetManifestResourceStream(resourceName))
            using (StreamReader reader = new StreamReader(stream))
            {
                string schema = reader.ReadToEnd();

                var task = JsonSchema4.FromJsonAsync(schema);
                task.Wait();
                return task.Result;
            }
        }

        private static void writeGeneratedSource(string name, string content) {
            string outputFile = outputDir + name + @".cs";

            // create the directory if it doesn't exist
            Directory.CreateDirectory(outputDir);

            File.WriteAllText(outputFile,
                              content);
        }
    }
```

**Comment by OlivierSohn** [comment]
At this point I took a different approach, relying on files, it seems to me that there is something missing to be able to use `FromJsonAsync` with multiple schema entities + references between them. This is covered by `FromFileAsync` however so I have a workaround.

**Comment by OlivierSohn** [comment]
yes but my wish was to be able to work without any file here :)

**Comment by RSuter** [comment]
I think you can also just use myBaseDir + "/myfakename.json" as path where myBaseDir is where the refs are looked up and myfakename.json does not exist ...

**Comment by OlivierSohn** [comment]
In my case the refs are not files, the refs are only available as embedded resources. I just reworded my initial text to be more precise about this.

**Comment by RSuter** [comment]
Then you have to implement an own reference resolver like: 

        public static async Task<JsonSchema4> FromJsonAsync(string data)
        {
            Func<JsonSchema4, JsonReferenceResolver> referenceResolverFactory =
                schema => new MyJsonReferenceResolver(new JsonSchemaResolver(schema, new JsonSchemaGeneratorSettings()));

            return await FromJsonAsync(data, null, referenceResolverFactory).ConfigureAwait(false);
        }

Where MyJsonReferenceResolver is your custom resolver (inherits from JsonReferenceResolver and overrides ResolveFileReferenceAsync())...

**Comment by OlivierSohn** [comment]
I see thanks for the support!

**Comment by RSuter** [comment]
You're welcome...
