### ISSUE TITLE
[Suggestion] Consider making the INotifyPropertyChanged inheritance + PropertyChangedEventHandler member optional

### ISSUE THREAD

**Issue by OlivierSohn** [RSuter/NJsonSchema#485]
I don't need them so I would like to be able to have an optimized code for my needs. (And couldn't find the option that disables it)

**Comment by RSuter** [comment]
![image](https://user-images.githubusercontent.com/2603405/30708398-11bcab72-9eff-11e7-867b-09ca30a26865.png)

**Comment by OlivierSohn** [comment]
Thank you for the quick support! Works perfectly.
