### ISSUE TITLE
Typescript client interfaces have full classes as children

### ISSUE THREAD

**Issue by danzel** [RSuter/NJsonSchema#494]
If you generate a typescript client and have it generate interfaces for the models, if the interfaces have models as children, those will have the solid types instead of the interface types.
I think these should use the interfaces as their types instead, to make the interfaces more friendly to use.
Will need to fix up some of the other parts that get generated to make this work.

Sound ok?
I’ll work on it later this week if so. Thanks!

**Comment by RSuter** [comment]
This is by design - I want these for just simpler initialization of the class (i.e. ctor instead of multiple property assignments, like C# type initializers). And for this it must be like this... 

You also can't just use "init()" because init takes the server JSON which may be different than the TS model (e.g. Upper Cased properties, string instead of date properties, etc.). If we would implement this, we would need to generate much more code (like "init()" but with the TS model names). 

Another problem is, that this would be a breaking change for existing users.

If you need this feature, I think we should add an option, e.g. GenerateJsonInitializers) which generate a whole new method "static FromJson(json)" which recursively assigns properties and also calls FromJson on referencing properties...

**Comment by danzel** [comment]
In my case I'd like to use the interface versions when declaring properties on react components.

At the moment I have to do something like:
```ts
//generated by NJsonSchema
interface IPerson {
    name: string;
    pet: Pet;
};
interface IPet {
    petType: string;
}

//My code
person: IPerson;
person = {
    name: 'bob',
    pet: new Pet({
        petType: 'cat'
    })
};

//And eventually, when calling the REST service (code generated by nswag)
client.someMethod(new Person(person));
```
The `new Pet` in the middle there is a bit ugly.

If we changed the `pet` property so it was `IPet`, this would be a breaking change, but I don't think it it would impact many people. `Pet` already implements `IPet`, so any existing code should just work fine as it is.

The constructor we generate at the moment is:
```ts
constructor(data?: IPerson) {
    if (data) {
        for (var property in data) {
            if (data.hasOwnProperty(property))
                (<any>this)[property] = (<any>data)[property];
        }
    }
}
```

I think the only thing we'd need to do is to add lines to construct all of the child classes:
```ts
constructor(data?: IPerson) {
    if (data) {
        for (var property in data) {
            if (data.hasOwnProperty(property))
                (<any>this)[property] = (<any>data)[property];
        }
        //Repeat this for each property that is an object
        if (data.pet && !(data.pet instanceof Pet)) {
            this.pet = new Pet(data.pet); //data.pet is guaranteed to implement IPet
        }
    }
}
```

We could also declare that the `pet` field on `Person` is `Pet`, not `IPet`, valid TS example:
```ts
interface ITestPerson {
    name: string;
    pet: ITestPet;
}

interface ITestPet {
    name: string;
}

class TestPerson implements ITestPerson {
    name: string;
    pet: TestPet;
}

class TestPet implements ITestPet {
    name: string;
}
```

As this works currently, the interface versions are not as useful (for me), most of the time I end up having to put constructors in my code anyway, where ideally I wouldn't have to if they were interfaces all the way down.

Sorry that is a lot to read, interested to hear your thoughts :)

**Comment by RSuter** [comment]
Yes, this is it! This would most probably not break existing users and support both - passing refs to existing Pets which are directly used (currently supported) and plain objects which are transformed to Pets... (new feature). 

Maybe we can do this on a single line/in a more compact form and with a safer check than instanceof (I had problems with instanceof after uglyfing/in older browsers), something like: 

     this.pet = data.pet && data.pet.toJSON ? new Pet(data.pet) : this.pet; 

What do you think?

**Comment by RSuter** [comment]
And also because we only need more code for references, arrays and dictionaries with DTOs the additional code is not that big of a problem...

**Comment by danzel** [comment]
IMHO instanceof would be better, it guarantees the type matches, but if you think it'll be trouble then using `.toJSON` as a test will probably be fine, hopefully no one sets that on the object they pass in :)
Will take a look tomorrow.

**Comment by RSuter** [comment]
Instanceof/toJSON is an implementation detail, I generally don't care what we choose in the end :-) - we just need to use the method which works in as many environments as possible (browsers, bundlers, minifiers, etc...).

**Comment by RSuter** [comment]
Ok thank you, will concentrate on other things... New NSwag release today with your other changes...

**Comment by RSuter** [comment]
There are two open questions: 

- [x] Should we use `toJSON` check instead of `instanceof`
    - If the object is coming from another "process" (i.e from iframe or popup) the type may be loaded twice and `instanceof` fails. 
    - Checking for toJSON is less generated code
    - This is why i think we shouldnt use instanceof
- [x] Should we put this whole feature behind a ConvertConstructorInterfaceData  setting (default: true)
    - Maybe we introduced a break or a case where not compilable code is generated and this way you can disable the feature until it is fixed
    - This new feature generates much more code which may not be desired (if the feature is not used)

What do you think?

**Comment by RSuter** [comment]
Can you review the changes in the branch "typescript-interface-children". If everything looks good, I'll release and upgrade NSwag so that we can test there :-)

**Comment by danzel** [comment]
Okay, I got a reason for using `instanceof`:
The code we generate now is not valid:
```this.cars[i] = item && !(<any>item).toJSON ? new Car(item) : item;```
But either of these are:
```this.cars[i] = item && !(item instanceof Car) ? new Car(item) : item;```
```this.cars[i] = item && !(<any>item).toJSON ? new Car(item) : <any>item;```

`item` comes from an `ICar[]`, so TS assumes it is an `ICar`.
TS is smart enough to know it is a `Car` if you use `instanceof`.

(Sorry, I missed this when making my original implementation of the feature)

Even if `instanceof` incorrectly returns `false`, we'll just create a new instance of the class and copy all the values over.
(`new Car(new Car(...))` is valid and works)
So... Not sure if that helps decide it :)

------

I updated my NSwag using this and updated the client in my app, and it did end up being a breaking change for me.
I was using the interface type, then relying on its children to be the concrete type, not the interface. Easy to fix however.
I expect if other people are generating interfaces there is a good chance they'll run in to this too.

-------

These two types not working feels bad... We can probably get away with it as you say, but it'll only be a matter of time before someone runs in to a case where this happens.
```ts
foo: Car[][];
bar: { [key: string] : Skill[]; };
```

------

As I should have probably just done in the first place, I've made an issue over on NSwag that is the real issue that pushed me to use the Class+Interface method https://github.com/RSuter/NSwag/issues/980

------

Other than the above, looks good.

**Comment by RSuter** [comment]
@grovesNL can you have a look on this? What is your opinion?

**Comment by RSuter** [comment]
**instanceof/toJSON check**

The problem is that `new Car(new Car(...))` may be equal but it is not the same - it is a clone. If a reference to the original car is mutated it will not be reflected in the person object and may lead to strange errors. But yes, a not working instanceof is definitely an edge case (I think?). 

**Breaking change**

We have the ConvertConstructorInterfaceData setting to have previous behavior. I want to enable this by default (and may have breaking changes) because I'm afraid that people will just not know about this feature (because there are many settings). If someone has problems with it, he can go to the release page/release notes and will find out about this and fix it or disable it. Upgrading to a newer version of NSwag is a explicit act and you should always diff the generated client to check the changes...

**Comment by grovesNL** [comment]
@RSuter If it's possible I think it's better to avoid `instanceof` and use duck typing instead. i.e. check for the presence of a method like you suggested, or add a private property containing the class name, etc. I agree it's an edge case for `instanceof` to fail, although it's usually subtle when it does fail.

Although this issue doesn't apply to me because I don't generate any model classes at all (only interfaces), except for the API client classes. I don't have a mix of classes/interfaces for the models.

**Comment by RSuter** [comment]
@danzel why is the generated code not valid? I cast to any exactly to avoid this problem?

**Comment by danzel** [comment]
Here is the result of ConstructorInterfaceTests.When_constructor_interface_and_conversion_code_is_generated_then_it_is_correct
https://gist.github.com/danzel/67455489f9adec99bca43bf1f4a959d4

Line 118 declares: `cars: Car[]`.
Line 130-135 are copying items from `data.cars` in to `this.cars`.
`data.cars` is an `ICar[]` (because data is `IMyClass`).

So `item` on line 132 is an `ICar`, and the ternary on line 133 is performing:
`this.cars = ... ? new Car(...) : <ICar>item;`
And you can't assign an `ICar` in to a `Car[]`.

`item` needs to be cast to `<any>` (or `<Car>`) :+1:

**Comment by RSuter** [comment]
Of course.. will fix this tomorrow

**Comment by danzel** [comment]
Another tiny nit:
```ts
for (var key in data.<#=property.PropertyName#>) {
```
Should be:
```ts
for (let key in data.<#=property.PropertyName#>) {
```

ClassTemplate.tt:42

**Comment by RSuter** [comment]
Ok, if fixed this. Is it ok for you to use `toJSON` do you think its fine now?

**Comment by danzel** [comment]
You can do a `<any>` cast to save a few chars.
`toJSON` should be fine.
I think this is good, can't test it properly till tomorrow.

**Comment by RSuter** [comment]
The cast is removed by the TS compiler anyway, so it's fine... I'll test it too with my projects...

**Comment by RSuter** [comment]
Bug: 

![image](https://user-images.githubusercontent.com/2603405/31277567-d99639da-aaa1-11e7-8c46-138c45e33c18.png)

possible null... must be set to []

**Comment by RSuter** [comment]
Ok, looks good in my projects, please test with the NSwag CI artifacts (or master branch)

![image](https://user-images.githubusercontent.com/2603405/31280127-9da8f7fa-aaab-11e7-8472-586144418d26.png)

**Comment by RSuter** [comment]
Currently this is disabled by default (to avoid breaking changes). 

I think we will flip this in the next major version of NSwag (then we should also use TS 2.0 by default)

**Comment by danzel** [comment]
Works great in our app :+1:

**Comment by RSuter** [comment]
Its released...

**Comment by RSuter** [comment]
Tahnks for your help

**Comment by RSuter** [comment]
https://github.com/RSuter/NJsonSchema/commit/4de768391c2858bc015b0907e1ffa59f5f935474

**Comment by thebestnom** [comment]
@RSuter how do you enable this in the cli?

**Comment by thebestnom** [comment]
It dosnt work for me if the class is inherited from another class
