### ISSUE TITLE
JsonSerializerSettingsTransformationMethod not used in InheritanceConverter

### ISSUE THREAD

**Issue by lisemon** [RSuter/NJsonSchema#501]
The serializer settings are neither applied on the `serializer`, `reader` or `writer` when using `InheritanceConverter`.

```
ReadJson(Newtonsoft.Json.JsonReader reader, System.Type objectType, object existingValue, Newtonsoft.Json.JsonSerializer serializer)
WriteJson(Newtonsoft.Json.JsonWriter writer, object value, Newtonsoft.Json.JsonSerializer serializer)
```

**Comment by RSuter** [comment]
At least read looks good to me (see tests)

**Comment by lisemon** [comment]
I am not really sure how to understand the two commits? That will not fix it entirely, right? You are using the tests in order to show how a setting can be applied to JsonConvert. I do not see the JsonConvert used anywhere. Please enlighten me 😄 

I have been looking into how to set the settings to be used in `ReadJson` and `WriteJson` in the generated code. A comment in the answer for this [stackoverflow entry ](https://stackoverflow.com/questions/8030538/how-to-implement-custom-jsonconverter-in-json-net-to-deserialize-a-list-of-base) explains that the `JsonReader` does not inherit the settings from the serializer, and it would be possible to use `serializer.Populate()` to do that.

"_The new JsonReader created in the ReadJson method does not inherit any of the original reader's configuration values (Culture, DateParseHandling, DateTimeZoneHandling, FloatParseHandling, etc...). These values should be copied over before using the new JsonReader in serializer.Populate()_"

However currently the serializer in the parameter in ReadJson and WriteJson parameter needs the settings to be applied, using the transform method.

So... This is what I have so far - I haven't explored the populate method yet, so for now it is just a stupid mapping between the `JsonSerializer` and `JsonReader` and `JsonWriter`. 

```
internal class JsonInheritanceConverter : Newtonsoft.Json.JsonConverter
    {
        private Newtonsoft.Json.JsonSerializerSettings _serializerSettings;

        ...
    
        public JsonInheritanceConverter()
        {
            _discriminator = DefaultDiscriminatorName;

            _serializerSettings = SerializerSettings.TransformSettings(new Newtonsoft.Json.JsonSerializerSettings());
        }
    
        public JsonInheritanceConverter(string discriminator)
        {
            _discriminator = discriminator;
            _serializerSettings = SerializerSettings.TransformSettings(new Newtonsoft.Json.JsonSerializerSettings());
        }
    
        public override void WriteJson(Newtonsoft.Json.JsonWriter writer, object value, Newtonsoft.Json.JsonSerializer serializer)
        {
            // only line added here
            writer = mapSerializerSettings(writer, _serializerSettings);

            try
            {
                _isWriting = true;
    
                var jObject = Newtonsoft.Json.Linq.JObject.FromObject(value, serializer);
                jObject.AddFirst(new Newtonsoft.Json.Linq.JProperty(_discriminator, value.GetType().Name));
                writer.WriteToken(jObject.CreateReader());
            }
            finally
            {
                _isWriting = false;
            }
        }
    
        ...
    
        public override object ReadJson(Newtonsoft.Json.JsonReader reader, System.Type objectType, object existingValue, Newtonsoft.Json.JsonSerializer serializer)
        {
            // only line added here
            reader = mapSerializerSettings(reader, _serializerSettings);

            var jObject = serializer.Deserialize<Newtonsoft.Json.Linq.JObject>(reader);
            if (jObject == null)
                return null;
    
            var discriminator = Newtonsoft.Json.Linq.Extensions.Value<string>(jObject.GetValue(_discriminator));
            var subtype = GetObjectSubtype(objectType, discriminator);
    
            try
            {
                _isReading = true;
                return serializer.Deserialize(jObject.CreateReader(), subtype);
            }
            finally
            {
                _isReading = false;
            }
        }
    
        ...

        private Newtonsoft.Json.JsonReader mapSerializerSettings(Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.JsonSerializerSettings settings) {
            reader.DateParseHandling = settings.DateParseHandling;
            reader.DateFormatString = settings.DateFormatString;
            reader.Culture = settings.Culture;
            reader.DateTimeZoneHandling = settings.DateTimeZoneHandling;
            reader.FloatParseHandling = settings.FloatParseHandling;
            return reader;
        }

        private Newtonsoft.Json.JsonWriter mapSerializerSettings(Newtonsoft.Json.JsonWriter writer, Newtonsoft.Json.JsonSerializerSettings settings)
        {
            writer.DateFormatHandling = settings.DateFormatHandling;
            writer.DateFormatString = settings.DateFormatString;
            writer.Culture = settings.Culture;
            writer.DateTimeZoneHandling = settings.DateTimeZoneHandling;
            writer.FloatFormatHandling = settings.FloatFormatHandling;
            writer.Formatting = settings.Formatting;
            writer.StringEscapeHandling = settings.StringEscapeHandling;
            return writer;
        }
    }
```

**Comment by RSuter** [comment]
Sorry the first commit was not for this issue :-)
The second is just a unit test where i tried to reproduce your problem - but couldnt...

We cannot use SerializerSettings.TransformSettings to get the settings here - we have to copy the settings from serializer but this is really bad...

Before we can fix this... we need a breaking unit test where we can reproduce the problem

**Comment by lisemon** [comment]
I see. So my actual issue is - maybe you can translate that into a test?
Ok, my actual issue is

**Precondition:**
Transform method:
```
public static JsonSerializerSettings TransformSettings(JsonSerializerSettings jsonSerializerSettings)
        {
            jsonSerializerSettings.DateParseHandling = DateParseHandling.DateTimeOffset;
            return jsonSerializerSettings;
        }
Class A {
    public DateTimeOffset created { get ; set; }
}

Class B {
    public C subclass { get; set;}
}

Class C {
    public DateTimeOffset created { get ; set; }
}

```

**Scenario 1 - OK on none nested object**
```
"A": {
    "created": "2017-06-06T00:00:00.123+10:00"
}
```

Deserialize and serialize again

Result: "created": "2017-06-06T00:00:00.123+10:00"
Expected: "created": "2017-06-06T00:00:00.123+10:00"

**Scenario 2 - Fails on nested objects**
```
"B": {
    "C": {
        "created": "2017-06-06T00:00:00.123+10:00"
    }
}
```

Deserialize and serialize again
Result: "created": "2017-06-06T16:00:00.123+02:00"
Expected: "created": "2017-06-06T00:00:00.123+10:00"

**Comment by RSuter** [comment]
Sorry, cant reproduce (see commit)
Are you really using the same settings for serialize/deserializing of the DTOs? Can you provide a sample project?

**Comment by lisemon** [comment]
Sooo. I am using couchbase to get documents, and it has a default serializer. I changed that default serializer, and can conclude that it is what is being passed to ReadJson and WriteJson in the InheritanceConverter. So no bug in your code. It just puzzles me that the ToJson and FromJson on the generated classes seems to never invoked, thus the settings are not affectuaed as such. But that's my problem. 😉 
Thanks for your patience.

**Comment by RSuter** [comment]
Yes, if the objects are serialized "from the outside" you have to manually ensure that the settings are correct...
