### ISSUE TITLE
Support for setting class access modifier on generated classes?

### ISSUE THREAD

**Issue by yberstad** [RSuter/NJsonSchema#509]
Hi!

NSwagStudio currently support setting "Client class access modifier". 

I asked in the NSwag repository, if it would be possible to add functionality in NSwagStudio to override the class access modifier on DTO objects as well.  But from what I understand, this is currently not supported because of restrictions in NJsonSchema.CodeGeneration that NSwag uses. 

Would it demand a lot of work to add support for custom class access modifier when generation c# classes?

Kind regards, Øyvind.

**Comment by RSuter** [comment]
Yes, dto classes/interfaces are generated in NJS, operations and clients in NSwag...

Should be pretty simple to add this option...

**Comment by yberstad** [comment]
Sweet, sounds good! Thanks for your quick responses and help. Would that option be added to the ClassTemplateModel? Is there anything I need to do / help with, or will this be added to a future release?

**Comment by RSuter** [comment]
Yes, see commit - ok like that?

**Comment by yberstad** [comment]
Very good!

**Comment by RSuter** [comment]
You can test with the NSwag ci build
