### ISSUE TITLE
Generating Enum without oneOf

### ISSUE THREAD

**Issue by alb3ric** [RSuter/NJsonSchema#527]
Hello,

I can't find if there is an option that would render an enum like this : 

```
{
  "title": "Procedure",
  "type": "object",
   "required": [
    "Gender"    
  ],
  "properties": {
    "Gender": {
          "type": "string",
          "enum": [
            "Male",
            "Female"
          ]
      }
  }
}
```

instead of with a oneOf   :

```
"Gender": {
      "oneOf": [
        {
          "$ref": "#/definitions/Gender"
        }
      ]
    },

```

Maybe this option does not exists. 

Thanks for the help

Regards,

**Comment by RSuter** [comment]
If there are no other properties, a $ref should be generated (not allOf). But if there is for example a "description" an allOf is generated, correct?

There's a big discussion around that: https://github.com/Azure/autorest/issues/2652

**Comment by RSuter** [comment]
Currently there is no option to change that, but I think there is no way around that but to add this option (which most users will confuse)

**Comment by RSuter** [comment]
Or do you want to completely inline enums?

**Comment by alb3ric** [comment]
I was thinking about completely inlining enum. I don't have access to my code untill Monday but if I remember I think I have a title on my enum, maybe that s what cause the oneof ?
Actually my problem with the oneof is that when I display the schema in jdorn/json-editor it add an empty entry in the select list of the enum, which does not happen when the enum is inline. But maybe actually the problem come from json-editor because if I read correctly, oneof means at least one element.
I ll look closer at it Monday

Thanks for your quick reply & your great work!

**Comment by RSuter** [comment]
The problem is that we mainly use schemas for code generation and for this scenario the enums must be referenced so that they are not generated multiple times... the main problem is that json schema is originally specified only for validation and not for rendering uis or generating code... but im sure we’ll find a solution. 

Have a nice weekend

**Comment by alb3ric** [comment]
Hello!

I look more deeply my problem and actually, I have a strange behavior. Let's say I have this class :

```
        public enum Gender
        {
            Male,
            Femal
        }

        public class Person
        {
            public Gender Genre { get; set; }
        }

```
it generate me this :

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {   
    "Genre": {
      "$ref": "#/definitions/Gender"
    }
  },
  "definitions": {
    "Gender": {
      "type": "string",
      "description": "",
      "x-enumNames": [
        "Male",
        "Femal"
      ],
      "enum": [
        "Male",
        "Femal"
      ]
    }   
  }
}
```

but if I specify a display name for my Gender property like this : 

```
        [Display(Name = "My Gender")]
        public Gender Genre { get; set; }
```
I got a oneof :

```
"Genre": {
      "title": "My Gender",
      "oneOf": [
        {
          "$ref": "#/definitions/Gender"
        }
      ]
    }
```
Which make my form not render the same the json-editor i use. I don't understand why adding a display name attribute will make my property a oneof.

Do you have any clue ? Is there any reason?

Thanks in adavance!

**Comment by RSuter** [comment]
The problem is described here: https://github.com/Azure/autorest/issues/2652

But I see that almost no tool is respecting the rule "$ref cannot have other properties" :-) - maybe NJS should also ignore this rule...

**Comment by RSuter** [comment]
https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/JsonSchemaGenerator.cs#L253-L274

**Comment by RSuter** [comment]
Explanation: The DisplayAttribute adds a new property "title" to the schema and thus $ref is not allowed anymore (because an object with $ref cannot have other properties). This is why we generate "oneOf" with $ref - which is semantically the same and which is allowed... The problem is, that most tools do not support this valid JSON Schema - and only support the invalid variant: 

```
"Genre": {
      "title": "My Gender",
      "$ref": "#/definitions/Gender"
    }
```

**Comment by alb3ric** [comment]
Yes, I looked in the code and found out that it was this part that was causing this behavior.
I understand your explanation.
Are you planning to ignore this rule or do you think we can think about a setting that would allow us to ignore this rule?

**Comment by RSuter** [comment]
This problem is killing me - it is very common to have this and there is no consensus how to handle this...

https://github.com/RSuter/NJsonSchema/issues/531

**Comment by alb3ric** [comment]
What about the possibility to render it like this :

{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {   
    "Genre": {
      "$ref": "#/definitions/Gender"
    }
  },
  "definitions": {
    "Gender": {
      "type": "string",
      "title": "My gender",
      "x-enumNames": [
        "Male",
        "Femal"
      ],
      "enum": [
        "Male",
        "Femal"
      ]
    }   
  }
}

With the title in the definitions. The json-editor render it like i want.
We should be able to specify a title on the enum with JsonSchemaAttribute for example.

**Comment by RSuter** [comment]
The problem here is that the title is on the wrong place: It is a description of the property and not the type itself... This would cause big problems with our code generators... I think we have to go with a setting.

**Comment by alb3ric** [comment]
or with [JsonSchemaExtensionData("title", "my gender")] on the enum.
But JsonSchemaExtensionData is not currently accepted on enum

**Comment by alb3ric** [comment]
http://jeremydorn.com/json-editor/?schema=N4IgJAzgxgFgpgWwIYgFwhgF0wB1QenwCsIB7AOwFpp5kA6UgJwHN8ATRpAM00oAYALPhqIkAYhAAaEJgCeOOGhCkARkThRMUkEjZsAlpn0UkAGwAKjUgsZG4ENFzMQ40nFZt2HqUAHE45IyKPuBBXEpi7HBc+uSGxuQQ+P7kbHCMIAC+mdJpMXFGFN5+AWkZIXIKShCYjLHM2kaYpsEgCLIABMyl6doAHpQBAK4IAHJICPZoANogALJmitIAYqKmIAC60sMIM/OL2qvI6xvZmUA&value=N4Ig4gpgdgThIC4QFkCGAbeBfIA=&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

**Comment by RSuter** [comment]
The problem is that **you want it to be on the property and not the type** so that you can specify a title per property and not only one... But adding this setting should solve your problem?

**Comment by RSuter** [comment]
BTW: You can fix this with a schema visitor: 

Sample: 
https://github.com/Picturepark/Picturepark.SDK.Playground/blob/master/src/AutoRestTransformer/Program.cs#L56

Visitor: 
https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Visitors/JsonSchemaVisitorBase.cs

**Comment by alb3ric** [comment]
Yes adding the setting solve my problem and is a far better solution.

What do you mean by fix this with a visitor? you mean I can add my title on the references thanks to a visitor? i'm going to look at it.

**Comment by RSuter** [comment]
With a custom visitor you can transform the schema so that it looks as expected... you can do this until the new setting is available...

**Comment by RSuter** [comment]
But keep in mind: If the enum is nullable, it will still output: 

"Gender": {
      "oneOf": [
        {
             "type": "null"
        },
        {
          "$ref": "#/definitions/Gender"
        }
      ]
    },

this will not change and should be supported because it is a valid JSON Schema!

**Comment by alb3ric** [comment]
Yes of course I understand this.
Thanks for all your replies. You are doing a great work

**Comment by alb3ric** [comment]
Do you have any planning for the new setting ?

**Comment by RSuter** [comment]
I just add it :)

**Comment by alb3ric** [comment]
wow ;) You are a boss!

**Comment by screig** [comment]
Leave a commentsfasfasf

**Comment by VeithBuergerhoff** [comment]
Tuning in for folks from the present times.

You can specify a JsonConverter like described [here](https://github.com/RicoSuter/NJsonSchema/wiki/Enums).
