### ISSUE TITLE
Generated typescript file contains unused imports

### ISSUE THREAD

**Issue by michael-biz** [RSuter/NJsonSchema#561]
We are using the `noUnusedLocals `and `noUnusedParameters `in our **tsconfig.json** `compilerOptions`. This leads to the following build error message:
```
ERROR in src/app/models/api.models.gen.ts(17,10): error TS6133: 'Observable' is declared but never used.
src/app/models/api.models.gen.ts(18,10): error TS6133: 'Injectable' is declared but never used.
src/app/models/api.models.gen.ts(18,22): error TS6133: 'Inject' is declared but never used.
src/app/models/api.models.gen.ts(18,30): error TS6133: 'Optional' is declared but never used.
src/app/models/api.models.gen.ts(18,40): error TS6133: 'InjectionToken' is declared but never used.
src/app/models/api.models.gen.ts(19,10): error TS6133: 'HttpClient' is declared but never used.
src/app/models/api.models.gen.ts(19,22): error TS6133: 'HttpHeaders' is declared but never used.
src/app/models/api.models.gen.ts(19,35): error TS6133: 'HttpResponse' is declared but never used.
src/app/models/api.models.gen.ts(19,49): error TS6133: 'HttpParams' is declared but never used.
```

Is there a way to either exclude the generated file or not produce the unused imports in the first place?

**Comment by RSuter** [comment]
NJsonSchema does not generate any TypeScript imports: 

https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.TypeScript/Templates/File.liquid

Do you generate with NSwag?

**Comment by michael-biz** [comment]
Yes, I'm generating the file using the NSwagStudio with the checkbox "Import required types (...)" checked.

**Comment by RSuter** [comment]
Hmm, and why are they not used? Have you disabled the generation of client classes?

**Comment by michael-biz** [comment]
Yes, we are only using the model classes (DTO types) at the moment and disabled the generation of client classes.

**Comment by RSuter** [comment]
For now, you can replace the current template with the latest template: https://github.com/RSuter/NSwag/wiki/Templates
