### ISSUE TITLE
NodaTime support misses LocaDateTime

### ISSUE THREAD

**Issue by jkonecki** [RSuter/NJsonSchema#569]
Support for NodaTime doesn't handle `LocalDateTime` type - properties will be generated as `strings` instead of dates.

`DefaultReflectionService` should be extended with ` type.FullName == "NodaTime.LocalDateTime"`

```
            if (type == typeof(DateTime) || 
                type == typeof(DateTimeOffset) || 
                type.FullName == "NodaTime.OffsetDateTime" || 
                type.FullName == "NodaTime.ZonedDateTime")
return JsonTypeDescription.Create(type, JsonObjectType.String, false, JsonFormatStrings.DateTime);
```

**Comment by RSuter** [comment]
Isnt a LocalDateTime property generated as type `string` and format `date` in JSON Schema and thus generated as DateTime in C# DTOs?

**Comment by jkonecki** [comment]
I'm generating TypeScript client and it comes up as `string`

**Comment by RSuter** [comment]
Ah no, only these noda types are handled: 

![image](https://user-images.githubusercontent.com/2603405/33277113-d93f7c7a-d397-11e7-8a99-f049b4eba6a1.png)

**Comment by RSuter** [comment]
So I think it should be handled the same as ZonedDateTime?

**Comment by jkonecki** [comment]
Yes, I updated my initial comment

**Comment by RSuter** [comment]
I'll add this...

**Comment by jkonecki** [comment]
Many thanks!

**Comment by RSuter** [comment]
Are other nodatypes missing?

**Comment by RSuter** [comment]
https://github.com/RSuter/NJsonSchema/commit/b42489ec02c6e958e760fe60bbd2cc01aedb4b97

**Comment by RSuter** [comment]
v9.10.10
