### ISSUE TITLE
Does not work with Newtonsoft 9.0.1

### ISSUE THREAD

**Issue by MurrayFoxcroft** [RSuter/NJsonSchema#573]
I get the below when trying to use Newtonsoft 9.0.1 - any higher version works but this does not help. Azure functions will only run on/up to Newtonsoft 9.0.1! 

Error1: 
FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Error2:
FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by RSuter** [comment]
Just directly install the desired Newtonsoft.Json version in the application and the application and NJS will run with the newer version...

**Comment by javieralpizar** [comment]
Hi! I'm facing this same exact error message using NewtonSoft 12 or any different version from 9.0.1 at a library project.

``` 
Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Current setup:
- .NET Framework 4.5
- Library project
- SDK-style csproj
- Newtonsoft.Json 12.0.3
- NJsonSchema 10.5.2

Tried also with the automatic redirect and others tags without luck:

``` xml
<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
<AutoUnifyAssemblyReferences>true</AutoUnifyAssemblyReferences>
```

The solution compiles referencing the version 12 at the Nuget "References" window. The unit test project runs fine using version 12 (checked the loaded dll at Modules). But when running and loading the DLL the exception is throw. Also validated with a breakpoint to see the Modules, the version 12 is correctly loaded into the AppDomain, but when using the schema validator at first time the exception shows up.

I've several packages using Newtonsoft 12 without problems and I don't like a downgrade to 9 just for this package (but it is the only solution that works).  Do you have any other configuration, clue or test I can try?

Regards,
