### ISSUE TITLE
DataAnnotations Required doesn't allow empty string

### ISSUE THREAD

**Issue by cortex93** [RSuter/NJsonSchema#617]
Hello,

In JsonSchema, when a property is required, it doesn't specify anything about the value and it can be empty
Non-empty string is designed with  
```
"non-empty-string" : {
          "type": "string",
          "minLength": 1
}
```
In MVC, Required means present and non-empty.
There is an argument on the RequiredAttribute, AllowEmptyStrings that allow non-empty string. 

Could it be possible to add this argument to true in the C# liquid class template when StringLengthMinimumValue = 0.

**Comment by RSuter** [comment]
Does this commit look correct to you (especially the changed unit tests)?

**Comment by cortex93** [comment]
Yes, looks good. Thanks
