### ISSUE TITLE
Is there a way to create Prism based model classes from JSON schema

### ISSUE THREAD

**Issue by WilfriedRicken** [RSuter/NJsonSchema#623]
Hi, we would like to create Prism based model classes from JSON schema. Something in princliple like that:

public class Foo: BindableBase
{
    public string Bar
    {
        get { return _bar; }
        set { SetProperty(ref _bar, value); }
    }
}

Inheritance should also work which means that inherited classes should not derive from BindableBase. In fact, even in the case of Inpc classes INotifyPropertyChanged should be implemented only in the base class, not the derived classes anymore.

As far as I can see I can create a new template factory and I can return different template strings for certain parts, so I could influence e.g. the way Inpc is implemented. However, the property InheritanceCode in ClassTemplateModel seems to be fixed, no way to influence it.

Thanks,
Wilfried

**Comment by RSuter** [comment]
Instead of writing a whole new template factory, you can also override some liquid templates within the LiquidTemplateFactory...

**Comment by RSuter** [comment]
If you also need to change the InheritanceCode, we should move this to a template...

**Comment by RSuter** [comment]
Maybe we should support prism directly?

**Comment by WilfriedRicken** [comment]
Yes, that's what I would need. I already created a new TemplateFactory where I only modify some of the templates, but the InheritanceCode can't be modified directly. And indeed, supporting Prism as a third option would be nice...

**Comment by WilfriedRicken** [comment]
Poco, Inpc, Prism

**Comment by RSuter** [comment]
We could move InheritanceCode into the liquid templates and remove the property, and additionally add the new style Prism as you proposed. This way it is directly supported and also open for more extensions in the future...

**Comment by RSuter** [comment]
FYI: https://github.com/RSuter/NJsonSchema/wiki/Templates

**Comment by WilfriedRicken** [comment]
Moving InheritanceCode to a template would be sufficient for me in the short term, adding a Prism style would be of course better in the long term...

**Comment by RSuter** [comment]
Hmm, why do we need to move the InheritanceCode in the first place? It's just used in "Class.liquid" - if you override this template, you can just replace InheritanceCode with your inline logic based on Prism classes like: 

Old: `{{InheritanceCode}}`
New Prism: `: {% if HasInheritance %}{{ BaseClassName }}{% else %}BindableBase{% endif %}`
New Inpc: `: {% if HasInheritance %}{{ BaseClassName }}, System.ComponentModel.INotifyPropertyChanged{% else %}System.ComponentModel.INotifyPropertyChanged{% endif %}`

**Comment by WilfriedRicken** [comment]
Oh, sure... I will do that in the short term...

**Comment by WilfriedRicken** [comment]
So, I changed some templates, and I have my Prism based classes working. That's fine. However, what must I do to create the same schema again from that classes? Prism.Mvvm.BindableBase is now the base class, and of course I get an addition in the schema like this one:

  "definitions": {
    "BindableBase": {
      "type": "object",
      "x-abstract": true,
      "additionalProperties": false
    }
  },
  "allOf": [
    {
      "$ref": "#/definitions/BindableBase"
    }
  ]

Any thoughts?

**Comment by RSuter** [comment]
There is an attribute JsonSchemaIgnoreAttribute but you cannot add it to BindableBase... you could however implement MyBindableBase : BindableBase add JsonSchemaIgnoreAttribute to MyBindableBase  and use MyBindableBase  everywhere...

**Comment by RSuter** [comment]
But because you cannot control BindableBase we could add ExcludedTypes to the settings with types which are ignored in the inheritance hierarchy...

**Comment by RSuter** [comment]
https://github.com/RSuter/NJsonSchema/commit/6eac96258077d81c13c819a5b2b91c486371d458

**Comment by RSuter** [comment]
I've added the ExcludedTypeNames setting to the schema generator settings so that you can exclude the BindableBase type from the inheritance hierarchy (without adding JsonSchemaIgnoreAttribute - which is not possible)...

**Comment by WilfriedRicken** [comment]
Thanks a lot! I'm amazed about the support!

**Comment by RSuter** [comment]
Just a question: Why do you need Prism based classes? Can't you just use the INPC classes with Prism?

**Comment by WilfriedRicken** [comment]
We use Prism heavily, and of course we could live with INotifyPropertyChanged. However, the partial class feature allows to extend the generated classes, and in these extensions we would like to have the Prism functionality. BTW, works perfectly!

**Comment by RSuter** [comment]
Makes sense :-) overwriting templates is just a patch and the problem is that you don't get fixes in the templates this way... we should add prism support out-of-the-box so you don't miss changes. What are all the required template changes?

**Comment by WilfriedRicken** [comment]
protected override string GetEmbeddedLiquidTemplate(string language, string template)
        {
            var result = base.GetEmbeddedLiquidTemplate(language, template);
            //Console.WriteLine($"{language}:{template}:{result}");

            if (template == "Class.Inpc")
            {
                result = "";
            }

            if (template == "Class.Inheritance")
            {
                result = "{% if HasInheritance %}: {{ BaseClassName }}{% else %}: Prism.Mvvm.BindableBase{% endif %}";
            }

            if (template == "Class")
            {
                result = result.Replace(
                    "set \n        {\n            if ({{ property.FieldName }} != value)\n            {\n                {{ property.FieldName }} = value; \n                RaisePropertyChanged();\n            }\n        }",
                    "set { SetProperty(ref {{ property.FieldName }}, value); }");
            }

            return result;
        }

Plus 

var schema = JsonSchema4.FromTypeAsync(type, new JsonSchemaGeneratorSettings { DefaultPropertyNameHandling = PropertyNameHandling.CamelCase, ExcludedTypeNames = new[] { "Prism.Mvvm.BindableBase" } }).Result;

Makes something like:

//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v9.10.27.0 (Newtonsoft.Json v10.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace ........
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v10.0.0.0)")]
    public partial class CreateOrder : Prism.Mvvm.BindableBase
    {
        private string _title;
        private string _orderText;
    
        [Newtonsoft.Json.JsonProperty("title", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Title
        {
            get { return _title; }
            set { SetProperty(ref _title, value); }
        }
    
        [Newtonsoft.Json.JsonProperty("orderText", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string OrderText
        {
            get { return _orderText; }
            set { SetProperty(ref _orderText, value); }
        }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static CreateOrder FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<CreateOrder>(data);
        }
    
    }
}
