### ISSUE TITLE
Couple of bugs in JsonReferenceConverter

### ISSUE THREAD

**Issue by Sumo-MBryant** [RSuter/NJsonSchema#640]
I was interested in trying out the `JsonReferenceConverter` but found a couple of issues:

https://github.com/RSuter/NJsonSchema/blob/830d6483caef79956d33de5ea42875110d8e887b/src/NJsonSchema/Converters/JsonReferenceConverter.cs#L23

This should be negated?

```csharp
public override bool CanWrite => !_isWriting;
```

---

Secondly attempting to emit a schema that is the property of something else fails due to the `JsonWriter` adding a `null` string after the schema.

https://github.com/RSuter/NJsonSchema/blob/830d6483caef79956d33de5ea42875110d8e887b/src/NJsonSchema/Converters/JsonReferenceConverter.cs#L55

I propose changing to this:

```csharp
                    var str = JsonSchemaReferenceUtilities.ConvertPropertyReferences(json);

                    if (writer.WriteState == WriteState.Property)
                    {
                        writer.WriteRawValue(str);
                    }
                    else
                    {
                        writer.WriteRaw(str);
                    }
```

**Comment by RSuter** [comment]
Good points, thank you. Can you please create a PR?

**Comment by RSuter** [comment]
This converter is not even used today :)

**Comment by RSuter** [comment]
v9.10.38
