### ISSUE TITLE
TypeScript: Exhaustiveness checing for enums breaks with EnumHandling.String

### ISSUE THREAD

**Issue by larskinn** [RSuter/NJsonSchema#647]
In the template for generating enums, when `DefaultEnumHandling = EnumHandling.String` is set, [the string value is cast to `any`](https://github.com/RSuter/NJsonSchema/blob/bda8b161c4827dcfdaf13d8672ebac29ee2b118b/src/NJsonSchema.CodeGeneration.TypeScript/Models/EnumTemplateModel.cs#L59).

This (among other things) removes a small nicety when working with TypeScript enums of [literal types (string, number, boolean, null, undefined)](https://github.com/Microsoft/TypeScript/pull/9407), namely exhaustiveness checking in switch statements.

There might well be a good reason to do the cast – please enlighten me if that's the case – but I present an example of my problem below.

### Example

Consider the C# enum

```csharp
public enum Status
{
    NotSet = 0,
    Approved = 1,
    Rejected = 2,
    Expired = 3
}
```

Which currently generates the following TypeScript enum (with EnumHandling.String)

```typescript
export enum Status {
    NotSet = <any>"NotSet",
    Approved = <any>"Approved",
    Rejected = <any>"Rejected",
    Expired = <any>"Expired",
}
```

Now, imagine a function for getting an icon for a `Status` in TypeScript

```typescript
type IconName = "question-mark" | "green-check" | "red-x" | "clock"

export function getStatusIcon(status: Status): IconName {
    switch (status) {
        case Status.NotSet:
            return "question-mark";
        case Status.Approved:
            return "green-check";
        case Status.Rejected:
            return "red-x";
        case Status.Expired:
            return "clock";
    }
}
```

### The problem
`getStatusIcon`, as written above, does not compile. It gives the following error:
> Function lacks ending return statement and return type does not include 'undefined'.

If we remove the `<any>` cast in the enum, `getStatusIcon` compiles.

The workaround is, of course, simple: adding a default case / ending return. But that means we lose the compile-time guarantee that if we add a new enum member, we must handle it in `getStatusIcon`.

**Comment by RSuter** [comment]
This any cast comes from the time when typescript didnt support string enums, see https://blog.rsuter.com/how-to-implement-an-enum-with-string-values-in-typescript/

Now that typescript directly supports string enums we can fix this. Do you know in which version typescript introduced string enums?

**Comment by RSuter** [comment]
Added in TS 2.4: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html

**Comment by larskinn** [comment]
Great! 🎉
Thanks for the quick response, and for your work on this project.
