### ISSUE TITLE
CSharpGenerator - Auto initialization of properties

### ISSUE THREAD

**Issue by nickcam** [RSuter/NJsonSchema#655]
First up nice work on the library, it's been very helpful!

When I'm using the following CSharpGeneratorSettings all of the properties that are reference types (ie complex objects and arrays) are auto initialized, I don't want this. I've tried all of the settings and always seems to auto initialize - must be missing something though.

for example:
```csharp
public partial class Person 
{
        public Department Dept { get; set; } = new Department();
}
```
The settings:
```csharp
var settings = new CSharpGeneratorSettings
{
         Namespace = options.Namespace,
         ArrayBaseType = "System.Collections.Generic.List",
         GenerateJsonMethods = false,
         ClassStyle = CSharpClassStyle.Poco,
         ArrayType = "System.Collections.Generic.List"
 };
```

Strangely though when I use NSwagStudio to generate from the same schema and settings, it isn't auto initializing the properties when generating. 
Any help greatly appreciated, Thanks!

**Comment by RSuter** [comment]
1. I think only not nullable properties are auto-initialized
2. NSwagStudio uses Swagger semantics to determine if a property is nullable (Swagger uses the required field and does not know null for types) whereas NJsonSchema runs in JSON Schema mode for code generation

**Comment by nickcam** [comment]
That explains the difference between tools...it's the fix as well actually. If I add a schema type of Swagger2 to the settings it generates without auto init. The schema I'm receiving is syntactically correct but not quite right.

```csharp
var settings = new CSharpGeneratorSettings
{
         Namespace = options.Namespace,
         ArrayBaseType = "System.Collections.Generic.List",
         GenerateJsonMethods = false,
         ClassStyle = CSharpClassStyle.Poco,
         ArrayType = "System.Collections.Generic.List",
         SchemaType = SchemaType.Swagger2
 };
```
You're a champion - thanks for the help!

**Comment by RSuter** [comment]
v9.10.38
