### ISSUE TITLE
It's not possible to deserialize ulong.MaxValue.

### ISSUE THREAD

**Issue by PeterTim** [RSuter/NJsonSchema#672]
I use nswag package to generate a contract for a class with ulong property. But after generation the ulong property became long.

it was:
public class A
{
public **ulong** N {get;set;}
}

became:
public class A
{
public **long** N {get;set;}
}

it looks like the problem is here:
https://github.com/RSuter/NJsonSchema/blob/1c902da998de466d76dc0ddea8d3ef9b81a268fa/src/NJsonSchema/Generation/DefaultReflectionService.cs#L49

**Comment by RSuter** [comment]
See http://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3

Same with OpenAPI: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#data-types

**Comment by RSuter** [comment]
To support that we'd need an additional custom field with this information...
