### ISSUE TITLE
XmlObject is not generated when the parent is not marked with XmlType attribute

### ISSUE THREAD

**Issue by emilw** [RSuter/NJsonSchema#684]
There is no XmlObject generated for properties that reference a type with an XMLTypeAttribute set when there parent misses the XmlType attribute.
```
 public class OrderRequestResponseDto
    {
        public string CorrelationKey { get; set; }

        public ConfirmationDataDto ResponseData { get; set; }
    }
```
Generates
```
"OrderRequestResponseDto": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "CorrelationKey": {
                    "type": "string"
                },
                "ResponseData": {
                    "$ref": "#/definitions/ConfirmationDataDto"
                }
            }
```
When it should generate this:
```
"OrderRequestResponseDto": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "CorrelationKey": {
                    "type": "string"
                },
                "ResponseData": {
                    "xml": {
                        "name": "ResponseData"
                    },
                    "$ref": "#/definitions/ConfirmationDataDto"
                }
            }
```
This whole reason for setting the xmlObject even though it should take the property name, was discussed here earlier: https://github.com/swagger-api/swagger-ui/issues/2610

**Comment by RSuter** [comment]
Is this fixing the Swagger output or just a workaround for Swagger UI?

**Comment by emilw** [comment]
It fixes the swagger output. It is a bug, as you see in the fix the parent type was sent in instead of property type. So i added a test case for it and changed it to property type.

**Comment by emilw** [comment]
If you check https://github.com/swagger-api/swagger-ui/issues/2610, i registered it when we introduced the xml support in the first place. This causes that we explicitly need to mark the property with the an XMLObject.Name that is the exact same as the property name, to avoid getting the Name from the type it reference.
Please check the test that i added and the new XML and you will see how it behaves.

**Comment by emilw** [comment]
@RSuter, when do you think this can be integrated in NSwag?

**Comment by RSuter** [comment]
Doing it now..

**Comment by RSuter** [comment]
Releasing: https://ci.appveyor.com/project/rsuter/nswag
