### ISSUE TITLE
Question: is it possible for existing field to be discriminant?

### ISSUE THREAD

**Issue by Dreamescaper** [RSuter/NJsonSchema#686]
Hi!

I'm wondering whether it is possible to have existing model field to be a discriminant?
Something like this:

```csharp
[JsonConverter(typeof(JsonInheritanceConverter("type")))]
[KnownType(typeof(ClassA))]
[KnownType(typeof(ClassB))]
public abstract class BaseClass
{
	public string Type {get;set;}
}
```

Currently it fails with `The JSON property 'type' is defined multiple times on type 'BaseClass'.`
Is it possible to avoid that verification?

Thing is that we use this field not only as discriminant, but for other needs as well (with modified discriminant values, though).

Thanks a lot!

**Comment by RSuter** [comment]
You're using the same field to store other values? Can you show an example?

**Comment by RSuter** [comment]
So the idea is to just expose the discriminator?

**Comment by Dreamescaper** [comment]
Yep, I'd just like to have discriminator value in model.
I think that could be achieved by removing check that value if already present in JsonSchemaGenerator.GenerateInheritanceDiscriminator, however I'm not sure how desired is that, or if there's any other way.

**Comment by Dreamescaper** [comment]
Seems like it works fine (checked locally). It is being written as any other property.
Any specific things you're thinking about?
