### ISSUE TITLE
Incorrectly generated default value for DateTime

### ISSUE THREAD

**Issue by qmicron** [RSuter/NJsonSchema#694]
```
            var schema = new JsonSchema4
            {
                Type = JsonObjectType.Object,
                Properties = { new KeyValuePair<string, JsonProperty>("DueDate", new JsonProperty
                {
                    Type = JsonObjectType.String,
                    Format = JsonFormatStrings.DateTime,
                    Default = DateTime.Now
                })}
            };

            var generator = new CSharpGenerator(schema);
            generator.Settings.GenerateJsonMethods = false;
            generator.Settings.GenerateDefaultValues = true;
            generator.Settings.ClassStyle = CSharpClassStyle.Poco;
            generator.Settings.GenerateDataAnnotations = false;

            var cs = generator.GenerateFile();
```

Generated property will get wrong default value

`public System.DateTime DueDate { get; set; } = "07.05.2018 11:20.05";`

Package - NJsonSchema.CodeGeneration.CSharp -Version 9.10.46

**Comment by RSuter** [comment]
Default cannot be an expression but only a fixed value - not supported by JSON Schema.

**Comment by RSuter** [comment]
You could override the JSON Schema generator and CSharpDefaultValueGenerator to handle this case with a custom extensions (or custom format string).

**Comment by qmicron** [comment]
But how can I inject customized CSharpValueGenerator into CSharpGenerator?

**Comment by RSuter** [comment]
Via settings object

**Comment by qmicron** [comment]
I am sorry, but CSharpGeneratorSettings expose only following extensions:

- IPropertyNameGenerator PropertyNameGenerator
- ITypeNameGenerator TypeNameGenerator
- IEnumNameGenerator EnumNameGenerator

I do not see how to override CSharpDefaultValueGenerator.

**Comment by RSuter** [comment]
Oh, this one is actually not changeable at the moment... (hard-coded)
