### ISSUE TITLE
TypeScrpit init(): A object property is processed as an array of objects.

### ISSUE THREAD

**Issue by homam1** [RSuter/NJsonSchema#697]
If the model in the API contains a field from type object, it is converting string to an array of charecters during the init.

The DTO in my case is: 
```
public class FilterDto 
    {
        public long FieldId { get; set; }
        public FilterOperator Operator { get; set; }
        public object Value { get; set; }
    }
```

The generated code is: 

```
export class FilterDto implements IFilterDto {
    fieldId: number | undefined;
    operator: FilterDtoOperator | undefined;
    value: any | undefined;
    viewId: number | undefined;
    id: number | undefined;

    constructor(data?: IFilterDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.fieldId = data["fieldId"];
            this.operator = data["operator"];
            if (data["value"]) {
                this.value = {};

// HERE IS THE PROBLEM. The string is broken down to an array of char
                for (let key in data["value"]) {
                    if (data["value"].hasOwnProperty(key))
                        this.value[key] = data["value"][key];
                }
            }
            this.viewId = data["viewId"];
            this.id = data["id"];
        }
    }

}

```
So, when the filter.value is a string, it is generated as an array of char.

**Comment by homam1** [comment]
Is there any workaround for this issue? Can I override the init function externally?
@RSuter

**Comment by homam1** [comment]
I see. Is there any way yo override the whole method and write it myself?

**Comment by RSuter** [comment]
Somehow it’s treated as dictionary: 
https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.TypeScript/Templates/Class.liquid#L41

**Comment by RSuter** [comment]
This is the condition for dictionary: 
https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/JsonSchema4.cs#L664

**Comment by RSuter** [comment]
Can you post the generated schema?

**Comment by homam1** [comment]
I already did in the post. I've posted the generated TypeScript code

**Comment by RSuter** [comment]
... the JSON Schema which is generated from the DTO.

**Comment by RSuter** [comment]
In this test everything looks fine: https://github.com/RSuter/NJsonSchema/commit/21ce1da947d5d017c7be190b96e6acefc78f8001

Also the generated output from the schema:
![image](https://user-images.githubusercontent.com/2603405/40440144-7d607a10-5ebd-11e8-92eb-5f86a5b67e6f.png)

**Comment by homam1** [comment]
Actually this happened after an update to the swagger library to the latest version. Can you please try with this schema? 

https://workiom-dev.azurewebsites.net/swagger

**Comment by RSuter** [comment]
What library are you using?

**Comment by homam1** [comment]
Swashbuckle.AspNetCore.SwaggerGen, Version=2.4.0.0

**Comment by mutzl** [comment]
Strings are generated as char arrays. But even worse - other types like boolean, are empty!
So this is really a show stopper.

**Comment by RSuter** [comment]
How exactly does the Swagger spec for this look like when generated by Swashbuckle? Somehow NJS treats it as dictionary when it's actually an object (objects are directly assigned, dictionaries are copied)
