### ISSUE TITLE
How to inject copyright headers into generated code?

### ISSUE THREAD

**Issue by gmar** [RSuter/NJsonSchema#700]
Hi there,

I'd like the C# code that is generated by nswag to include our companies copyright headers at the top of each file. I'm unable to accomplish this at the moment and I'm not sure whether I'm doing anything wrong, or not...

I have added a 'TemplateDirectory' to my *.nswag file...
` "codeGenerators": {`
`    "swaggerToCSharpClient": {`
`      "TemplateDirectory": "templates",`
`      ...`

The 'templates' directory contains a file named "File.liquid".
File.liquid contains this...
`/*`
`Copyright 2018 MyCompany etc etc.`
`*/`
`{% template %}`

...as suggested by: https://github.com/RSuter/NJsonSchema/wiki/Templates

When I then run nswag.exe, it throws an error claiming that...

> DotLiquid.Exceptions.SyntaxException: Unknown tag 'template'

I've tried a bunch of other things like...
`{% template -%}`
`{{ template }}`
`{{ template File.liquid }}`
...but with no success.

Any help would be appreciated.

**Comment by RSuter** [comment]
This is clearly a bug...

**Comment by RSuter** [comment]
Here its not correctly replaced: 
https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration/DefaultTemplateFactory.cs#L148

Try `{% __njs_template %}` but it probably wont work as it seems the feature is completely broken...

**Comment by RSuter** [comment]
v9.10.49

**Comment by RSuter** [comment]
And use `{% template %}`

**Comment by RSuter** [comment]
Is this now working for you?

**Comment by gmar** [comment]
Hi Rico,

We haven’t tried yet.
We’re due for another round of work in this area, perhaps in a few weeks’ time.
I’ll let you know how it goes.

Thanks,
Guy

**Comment by rhermans2004** [comment]
I tried using {% template %} using NJSONSchema 10.9.0, but it doesn't seem to work. My workaround is to copy the full content of  [File.Liquid](https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.CSharp/Templates/File.liquid) locally... which is not ideal solution.
