### ISSUE TITLE
Discriminator not set in case of inherited classes

### ISSUE THREAD

**Issue by gschmarri** [RSuter/NJsonSchema#709]
We faced the problem, that the discriminator is not set in case of inherited classes.
We replaced **line 20** in file **NJsonSchema/src/NJsonSchema.CodeGeneration.TypeScript/Templates/Class.liquid** by removing the 'Model.' prefix.

Current:
{% if GenerateConstructorInterface or Model.HasBaseDiscriminator -%}
Suggestion:
{% if GenerateConstructorInterface or **HasBaseDiscriminator** -%}

That solved our problem.

Is that a proper solution for our problem?

**Comment by RSuter** [comment]
Indeed it seems that i missed to remove the model. prefix when i migrated to liquid... strange that noone run into this earlier (i use ctor interfaces).
