### ISSUE TITLE
Override ConvertToClassCode and ConvertToJavaScriptCode

### ISSUE THREAD

**Issue by jfernandeze** [RSuter/NJsonSchema#715]
Hello

I'd like to override the ConvertToClassCode and ConvertToJavascriptCode. Is it possible?

**Comment by RSuter** [comment]
You can override the templates: https://github.com/RSuter/NJsonSchema/wiki/Templates

**Comment by jfernandeze** [comment]
If you check  NJsonSchema/src/NJsonSchema.CodeGeneration.TypeScript/Templates/Class.liquid in the line 145 i'd like to change the functionality of **ConvertToJavaScriptCode**

`        /// <summary>Gets the convert to JavaScript code.</summary>
        public string ConvertToJavaScriptCode
        {
            get
            {
                var typeStyle = _settings.GetTypeStyle(_parentTypeName);
                if (typeStyle != TypeScriptTypeStyle.Interface)
                {
                    return DataConversionGenerator.RenderConvertToJavaScriptCode(new DataConversionParameters
                    {
                        Variable = "data[\"" + _property.Name + "\"]",
                        Value = typeStyle == TypeScriptTypeStyle.Class ? "this." + PropertyName : PropertyName + "_",
                        Schema = _property.ActualTypeSchema,
                        IsPropertyNullable = _property.IsNullable(_settings.SchemaType),
                        TypeNameHint = PropertyName,
                        Resolver = _resolver,
                        NullValue = _settings.NullValue,
                        Settings = _settings
                    });
                }

                return string.Empty;
            }
        }`

**Comment by RSuter** [comment]
There is also a template which is used by this code...
