### ISSUE TITLE
output multiple files for each class and interface

### ISSUE THREAD

**Issue by jfernandeze** [RSuter/NJsonSchema#716]
I wonder if we can generate the output with multiple files. this would be wonderful

**Comment by RSuter** [comment]
This will get you a collection of classes and interfaces: https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.CSharp/CSharpGenerator.cs#L50

**Comment by jfernandeze** [comment]
yes.. but if I use NSwagStudio I can not do it.

**Comment by RSuter** [comment]
Yep, i know, it's not there yet... It has to be implemented in NSwag.Core and all the tooling (e.g. CLI, etc.)

**Comment by lecoque** [comment]
@RSuter so how to use it now?

**Comment by RSuter** [comment]
@lecoque it's only implemented in NJS yet, the feature has to be used by NSwag and exposed via CLI, UI, etc. also the logic to update existing files is not simple as the generator may need to remove files (but only generated ones, etc.)

**Comment by RSuter** [comment]
Ref: https://github.com/RSuter/NSwag/issues/1398

Closing here, because it's implemented in NJS and must be used in NSwag...
