### ISSUE TITLE
A 'format' attribute in JSON schema

### ISSUE THREAD

**Issue by sashayudaev** [RSuter/NJsonSchema#725]
Whenever I try to generate a schema from a class that contains double or integer properties, I do get a **format** attribute attached to these properties.

For example:
```
{
  "title": "SomeClass",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "Number": {
      "type": "number",
      "format": "double"
    }
  }
}
```

So I'm curious if there's any way I can force to ignore adding this attribute to a schema?

**Comment by RSuter** [comment]
I think the easiest way would be to implement an own reflection service which inherits from DefaultReflectionService and overrides GetDescription and which just modifies the format but uses the base implementation:

https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/DefaultReflectionService.cs#L77

**Comment by sashayudaev** [comment]
Ayy thanks, saved my time!
