### ISSUE TITLE
Null reference when generating json schema for IEnumerable with nullable items

### ISSUE THREAD

**Issue by Oposow** [RSuter/NJsonSchema#726]
For below object JsonSchema4.FromTypeAsync throw null reference exception in **DefaultReflectionService.GetDescription** in line **143**. 

The exception is thrown when serializing **OneOf** property

`public enum FuelCardSource
    {
        Orlen = 1,
        CircleK = 2
    }

    public class GetFuelCardsParams
    {
        public FilterParams<int?> Id { get; set; }
        public FilterParams<bool?> IsActive { get; set; }

        public FilterParams<string> CarModel { get; set; }
        public FilterParams<string> CarRegistrationNumber { get; set; }

        public FilterParams<string> DepartmentName { get; set; }
        public FilterParams<string> UserName { get; set; }

        public FilterParams<FuelCardSource?> Source { get; set; }
        public FilterParams<DateTime?> ValidFrom { get; set; }
        public FilterParams<DateTime?> ValidTo { get; set; }

        public FilterParams<string> Number { get; set; }

        public FilterParams<int?> UserId { get; set; }
        public FilterParams<int?> CarId { get; set; }
        public FilterParams<int?> DepartmentId { get; set; }

        public FilterParams<string> Notes { get; set; }
        public PagingParams Paging { get; set; }
    }

    public class FilterParams { }

    public class FilterParams<T> : FilterParams
    {
        public T Equal { get; set; }
        public T NotEqual { get; set; }

        public T LessThan { get; set; }
        public T LessThanOrEqual { get; set; }

        public T GreaterThan { get; set; }
        public T GreaterThanOrEqual { get; set; }

        public T HasFlag { get; set; }
        public T HasntFlag { get; set; }

        public bool? HasValue { get; set; }

        public IEnumerable<T> OneOf { get; set; }
        public T Contains { get; set; }

        public string StartsWith { get; set; }
        public string ContainsAllWords { get; set; }

        public SortDir? Sort { get; set; }
    }

    public enum SortDir
    {
        Desc = 0,
        Asc = 1
    }

    public class PagingParams
    {
        public int? Skip { get; set; }
        public int? Take { get; set; }
    }`

Changing 
`                var typeDescription = GetDescription(type.GenericTypeArguments[0], parentAttributes.Where(a => !(a is JsonSchemaTypeAttribute)), settings);
`

to
`                var typeDescription = GetDescription(type.GenericTypeArguments[0], (parentAttributes ?? new Attribute[0]).Where(a => !(a is JsonSchemaTypeAttribute)), settings);
`
Could you fix this bug and create new package available to download via nuget, please?

Thank in advance! :)

**Comment by RSuter** [comment]
v9.10.57

**Comment by zhongxun** [comment]
Could you also update NSwag and NSwag.MSBuild 11.17.16 which depends on NJsonSchema v9.10.56.0?

Currently they have same error when generating IEnumerable nullable

**Comment by RSuter** [comment]
Sure, in 1-2 hours

**Comment by zhongxun** [comment]
Really appreciate! It was fast.
