### ISSUE TITLE
Unable to define array items by $ref according to draft4

### ISSUE THREAD

**Issue by Mats666** [RSuter/NJsonSchema#749]
I have a problem with define array item by $ref. Using Newtonsoft Json Schema I can write this code:
```
{
  "title": "JSON Schema for entity metadata JSON file format",
  "definitions": {
    "arrayElement": {
      "type": "object",
      "properties": {
        "someProperty": { "type": "string" },
        "someProperty1": { "$ref": "#/definitions/object1" }
      },
      "object1": {...}
    }
  },
  "type": "object",
  "properties": {
    "SomeArray": {
      "type": "array",
      "items": { "$ref": "#/definitions/arrayElement" }
    }
  }
}
```
And according to code above I can get JSchema with right array elements which validate correctly. But NJsonSchema cannot parse (without exceptions) this json code and I get empty array Items in JsonSchema4 object. Array elements can be really big with links ($ref) to another items in definitions
Is it possible to define array elements like this or there is another way to do it?

**Comment by RSuter** [comment]
Looks good to me: 

![image](https://user-images.githubusercontent.com/2603405/43266139-dcec5698-90ea-11e8-9003-7fd6aba82038.png)

**Comment by Mats666** [comment]
After some attempts I understand that it work correctly and validation was succesfully done but the items of 'SomeArray' in JsonSchema4 object was empty (look through quick watch "Shift + F9"). This confused me. 

![image](https://user-images.githubusercontent.com/41650503/43303453-87b628dc-9178-11e8-8633-479435a60a4d.png)

Properies doesn't exists in item object. And items collection is empty.

Thanks for response.

**Comment by RSuter** [comment]
The “problem” is that it uses $refs. Use ActualSchema to dereference or Reference to get the referenced schema...

**Comment by Mats666** [comment]
But validation work correct. Is it normal?

**Comment by RSuter** [comment]
Yes, everything is fine... If you have a { $ref: ... } then NJS creates a new JsonSchema4 object with a Reference to another JsonSchema4 object, this way you can fully work with the schema in C# and also with refs (we cannot just use C# references as the serializer would not know if it's a $ref or just a regular inline schema)… This is why we have the properties Reference, HasReference and ActualSchema etc...

**Comment by Mats666** [comment]
Thank you very much. The issue is closed.
One question. In future are you going to add "if then else" in Json Schema according to the draft v7?
Because it is really useful especially when you add required fields based on value in enum for example from another field.

**Comment by RSuter** [comment]
You're welcome. 

There are surely plans to support v6 & v7, but I mainly use NJS in conjunction with NSwag (http://nswag.org) to generate code and if/else is not supported by Swagger and only needed for validation. But if you have time, please create a PR with that along with some unit tests etc. help for v6/v7 features is greatly appreciated!

Also see: https://github.com/RSuter/NJsonSchema/issues/574

**Comment by Mats666** [comment]
I'm sorry, but what do you mean when asks me about PR?

**Comment by RSuter** [comment]
It would be great if you have time to implement if/then (i.e. extend the model and extend the validator) and create a PR with that - if you have time...
