### ISSUE TITLE
JsonSchema4.FromData() doesnt exist

### ISSUE THREAD

**Issue by lorranpalmeira** [RSuter/NJsonSchema#750]
Hello,

I think that method FromData() doesnt exist, but if you read README.md you see:

Generate JSON Schema from sample JSON data (JsonSchema4.FromData())

Maybe the actual method is  JsonSchema4.FromSampleJson();

Please when possible fix it.

**Comment by RSuter** [comment]
Its FromSampleJson()

**Comment by lorranpalmeira** [comment]
Yes, I realized.

Thanks
