### ISSUE TITLE
Retain validation attributes

### ISSUE THREAD

**Issue by cbordeman** [RSuter/NJsonSchema#789]
Attributes such as [Required], [Range], [StringLength(5)] from the System.ComponentModel.DataAnnotations namespace should be retained in the generated client side models so validation can be performed.

**Comment by RSuter** [comment]
Duplicate of: 
https://github.com/RSuter/NJsonSchema/issues/308

**Comment by cbordeman** [comment]
Sorry, was asked to move this and didn't realize was already implemented.
