### ISSUE TITLE
[Feature] Ability to infer schema from a JSON string

### ISSUE THREAD

**Issue by brandonh-msft** [RSuter/NJsonSchema#805]
All I want is to be able to take a JSON string that represents a JSON object/array/etc and spit out a JSON schema definition for that object. 

As near as I can tell, in order to do this with this project I'd have to create intermediate c# classes/files, then have _those_ used to generate the schema. It'd be great if I could avoid the intermediate step.

Thanks!

**Comment by brandonh-msft** [comment]
looks like it's here: NJsonSchema.Generation.SampleJsonSchemaGenerator

**Comment by RSuter** [comment]
Exacly, do you know a better name?

**Comment by brandonh-msft** [comment]
Maybe `SampleDataJsonSchemaGenerator`? probably not worth a breaking change, though. Maybe make it more prevalent in README.md?

The astonishing thing is this tidbit showed up in **none** of about 6 google searches I tried to find an answer. Might also be worth the time to throw it in to some of the StackOverflow questions out there?

**Comment by RSuter** [comment]
Added wiki page: https://github.com/RSuter/NJsonSchema/wiki/SampleJsonSchemaGenerator

**Comment by brandonh-msft** [comment]
perfect! Thanks!
