### ISSUE TITLE
How to know type and format of array items

### ISSUE THREAD

**Issue by vhatsura** [RSuter/NJsonSchema#809]
Hello.

First of all big thanks for NJsonSchema and NSwag libraries. These libraries are awesome.

In my case it can be a question not an issue.

I want to know `type` and `format` values of my items in array. I tried to write a little demo to know how can I get `Items` definition from jsonSchema.
Demo:
```csharp
public class Person
{
    public IList<Guid> Ids { get; set; }
}

var schema = await NJsonSchema.JsonSchema4.FromTypeAsync<Person>();

schema.Properties["Ids"].ToJson().Dump();
```
Output:
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": [
    "array",
    "null"
  ],
  "items": {
    "type": "string",
    "format": "guid"
  }
}
```

The first strange issue for me is `null` in type property (also I'm wondering that `type` can be array of values).
The second issue is `Items` of `schema.Properties["Ids"]` in code is empty.
```csharp
schema.Properties["Ids"].Items.Dump();
(0 items)

```

After dumping whole jsonSchema of Ids property definition I didn't find any way how I can get items definition.

What is wrong with my code?

**Comment by RSuter** [comment]
I think it's 

- Item => Schema of an array item
- Items => Schemas of a tuple array (i.e. each element has another schema)

**Comment by vhatsura** [comment]
@RSuter, thanks, Item actually has all required info for me)
From `JSON the "items" property can either be a schema {} (Item) or list of schemas [{}, {}] (Items)` perspective, I believe in case of one schema it can be more convenient to have list with one schema inside.

**Comment by RSuter** [comment]
> I believe in case of one schema it can be more convenient to have list with one schema inside.

But then I dont know if it's a tuple with one element or just an array when serializing the schema... so that's not an option.

**Comment by vhatsura** [comment]
Yes, agree with you.

And what about the first question?

> The first strange issue for me is null in type property (also I'm wondering that type can be array of values).

**Comment by RSuter** [comment]
> The first strange issue for me is null in type property

Null type is only allowed in JSON Schema but not in Swagger/OpenAPI

> also I'm wondering that type can be array of values

That is allowed in JSON Schema but not in Swagger/OpenAPI (dont ask...)

I think FromTypeAsync takes a setting object, just change the SchemaType to Swagger (v2) or OpenApi (v3)

**Comment by RSuter** [comment]
`IList<Guid>` is nullable that's why it's adding null - add [Required] or [NotNull] to the property to make it not nullable in the schema.

**Comment by vhatsura** [comment]
got it. Thanks a lot again.
Sorry for inconvinience from my side and some stupid questions ;)

Issue can be closed

**Comment by RSuter** [comment]
They are not stupid, its just not documented well enough - feel free to improve the wiki 🙂

Here are the supported attributes: https://github.com/RSuter/NJsonSchema/wiki/JsonSchemaGenerator
