### ISSUE TITLE
PropertyModel.IsNavigationProperty or .IsObject for better templating in CodeGeneration.CSharp: 

### ISSUE THREAD

**Issue by Arsync** [RSuter/NJsonSchema#848]
Need (or how?) to add some additional check to properties of linked entities (navigation properties in T4, objects in Json). My quick solution is to compare Property.Type with PropertyName, but it so strange: if there exists entity type like a 'Product', property name must be 'Product' to add the extra-logic (in combination with Trackable Entities project).

Part of the Class.liquid template:

```
{{PropertySetterAccessModifier}}set 
{
	if ({{ property.FieldName }} == value)
		return;
	{{ property.FieldName }} = value;		
{%      if property.PropertyName == property.Type %}
	{{ property.PropertyName }}ChangeTracker =
		{{ property.FieldName }} == null
			? null : new ChangeTrackingCollection<{{ property.Type }}>
		{
			{{ property.FieldName }}
		};
{%      endif %}
	NotifyPropertyChanged();
}
```
Maybe pass JsonObjectType.Object to visible properties of PropertyModel? Like
` {%      if property.IsObject %} `
or
` {%      if property.IsSubclassOf("EntityBase") %}`
or
` {%      if property.IsEntityType %}`

**Comment by RSuter** [comment]
Add IsObject property to model, https://github.com/RSuter/NJsonSchema/pull/851
