### ISSUE TITLE
JsonInheritanceConverter discriminator name is case sensitive

### ISSUE THREAD

**Issue by stukselbax** [RSuter/NJsonSchema#849]
We have DTO with exposed discriminator property, and also we apply the camelCase option in serialization setting. I would like to specify your converter as follow:

```c#
    [JsonConverter(typeof(JsonInheritanceConverter), nameof(Type))]
    public abstract class MyBaseDTO
    {
        public string Type { get; set; }
    }
```

This working fine until the discriminator key is exactly "Type" string. This is becase of call to `GetValue` does not use any string comparasion, and default is used (which is probably case-sensitive):

https://github.com/RSuter/NJsonSchema/blob/9996a0bd5faadd782b92ae4d486f32431dca8bd7/src/NJsonSchema/Converters/JsonInheritanceConverter.cs#L162

When we trying to follow camelCase convention, converter fails with `ArgumentNullException`.

```json
{
    "innerProperty": "bla-bla-bla",
    "type": "InnerType"
}
```

This can be handled using "type" as the name for discriminator key.
Will you consider to respect the casing for the discriminator key in such case? [GetValue](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Linq_JObject_GetValue_1.htm) has overload with StringComparasion parameter.

**Comment by RSuter** [comment]
Just use

     [JsonConverter(typeof(JsonInheritanceConverter), "type")]

so that the property name is correct... using StringComparasion  would be just an ugly hack/patch
