### ISSUE TITLE
Inherited from List  rendered as object

### ISSUE THREAD

**Issue by hmvs** [RSuter/NJsonSchema#874]
Following the discussion https://github.com/RSuter/NSwag/issues/1672
Inherited classes from `List` rendered as simple `object`. 
Example: 
`public class SomeModelCollectionResponse : List<SomeModel> { }`

**Comment by RSuter** [comment]
So the output of my test is clearly wrong: 

![image](https://user-images.githubusercontent.com/2603405/51256261-4934b500-19a5-11e9-82ad-31e000f3caa4.png)

"items" is set so the type must be "array" - this output is never correct...

**Comment by hmvs** [comment]
If you want you can commit this unit test or send me, I can try to fix it at home.

**Comment by RSuter** [comment]
Do you think the linked pr solves your issue?

**Comment by hmvs** [comment]
Works. Thanks again :)
