### ISSUE TITLE
Reading an open api 3 schema from disk

### ISSUE THREAD

**Issue by nojaf** [RSuter/NJsonSchema#903]
I'm trying to read a open api 3.0 schema from disk and it always contains zero items.

```csharp
            var x = new JsonSchemaGeneratorSettings
            {
                SchemaType = SchemaType.OpenApi3
            };
            var factory = JsonReferenceResolver.CreateJsonReferenceResolverFactory(x);
            var schema = await JsonSchema4.FromFileAsync(@"C:\temp\NJsonSchema\schemas\itineraries.json", factory);
```

I checked my schema, it is valid and I get output in NSwag Studio. What am I doing wrong here?

**Comment by RSuter** [comment]
Its not a json schema file but an openapi/swagger file, use

SwaggerDocument.FromFileAsync(...)

From NSwag.Core

**Comment by nojaf** [comment]
Hi, thanks for answering my question in three places.
Much appreciated.
