### ISSUE TITLE
DateTimes with milliseconds and regex

### ISSUE THREAD

**Issue by evman182** [RSuter/NJsonSchema#906]
Since the change at one point that set `DateParseHandling` to `None` was later removed, validating properties with datetime values that have a RegEx pattern that expects milliseconds to be there does not work. I was able to work around this by parsing the JSON myself first with those serializer settings, but I still would think this would be considered a bug.

Here's an example schema and json:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "my_datetime"
  ],
  "properties": {
    "my_datetime": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$"
    }
  }
}

{
  "my_datetime": "2018-12-19T16:58:07.270Z"
}
```

**Comment by RSuter** [comment]
You need to use the Validate(string) with a string parameter to correctly validate datetime with custom regexes, are you doing that?

**Comment by RSuter** [comment]
> that set `DateParseHandling` to `None` was later removed

What do you mean by that? Has this been removed from NJsonSchema?

**Comment by evman182** [comment]
https://github.com/RSuter/NJsonSchema/pull/268

but I don't think the author of the PR is correct about JToken.Parse

**Comment by RSuter** [comment]
Oh shit, you are right... this shouldnt have been removed.

**Comment by RSuter** [comment]
Released soon: https://github.com/RSuter/NJsonSchema/pull/907
